# Ghidra Jython dumper — GW item-mod tables
# =========================================
# Run this INSIDE Ghidra (Script Manager, or via the Ghidra MCP run_script_inline),
# with the analyzed Guild Wars image open (Gw.wasm preferred — symbol-rich; a
# stripped Gw.exe works too once the addresses below are re-resolved for that image).
#
# It dumps the game's authoritative item-mod label tables + the per-EItemType
# upgrade-slot table to a Python data module. Values are ETextStr string-table IDs
# (language-independent keys); decode them to display text at runtime with
# Py4GWCoreLib.native_src.internals.string_table.decode().
#
# WHY: replaces a hand-maintained JSON. The data is the game's own, re-dumpable per
# patch. See docs/item_mods/06_game_mod_engine_RE.md for how these addresses were found.
#
# ADDRESSES are from Gw.wasm (2026-07). For a different image, re-resolve each base by
# decompiling the matching ConstXxx function and reading the final `base[index]` load
# (and the count from its `index < N` bounds assertion). The Const* accessors are:
#   ConstItemGetColorString / ConstItemGetDescriptionText / ConstAttribGetName /
#   ConstGetCharDamageText / ConstGetCharDamagePrefix / ConstGetCharKind /
#   ConstGetCharKindSlaying / ConstGetCharConditionName
# and the caps table is used by ItemCommon::TestUpgradeCompatibility.

import os

# Where to write the generated module (edit as needed; Ghidra runs on the same host).
OUT_PATH = r"C:\Users\Apo\Py4GW_Reforged\docs\item_mods\tools\game_mod_tables.py"

# (enum_name, array_base, count, stride_bytes) — ETextStr id is the uint32 at offset 0.
LABEL_TABLES = [
    ("EItemColor",        0x0019c3c0, 14,  4),      # ConstItemGetColorString   (color < ITEM_COLORS)
    ("EItemDescription",  0x0019da70, 360, 4),      # ConstItemGetDescriptionText (description < ITEM_DESCRIPTIONS)
    ("ECharAttrib",       0x0018be28, 51,  0x14),   # ConstAttribGetName (20-byte struct/entry, id at +0)
    ("ECharDamageText",   0x002796e0, 14,  4),      # ConstGetCharDamageText
    ("ECharDamagePrefix", 0x002796a0, 14,  4),      # ConstGetCharDamagePrefix
    ("ECharKind",         0x00279730, 12,  4),      # ConstGetCharKind
    ("ECharKindSlaying",  0x00279760, 12,  4),      # ConstGetCharKindSlaying (slaying/"vs. species" text)
    ("ECharCondition",    0x00279670, 9,   4),      # ConstGetCharConditionName
]

# Per-EItemType upgrade-slot / capability table (used by TestUpgradeCompatibility):
# record stride 0x10; first uint32 is a capability bitmask; bits 6/7/8 gate the
# prefix / suffix / inherent upgrade slots for that item type.
CAPS_BASE = 0x0015c6fc
CAPS_STRIDE = 0x10
CAPS_COUNT = 46                                     # EItemType 0..45 (Costume_Headpiece is last; 46+ reads past the table)
CAP_BIT_PREFIX = 6
CAP_BIT_SUFFIX = 7
CAP_BIT_INHERENT = 8


def rd_u32(addr):
    # getInt/toAddr come from Ghidra's FlatProgramAPI (available in Script Manager scripts).
    return getInt(toAddr(addr)) & 0xFFFFFFFF


def dump():
    out = []
    out.append("# AUTO-GENERATED by docs/item_mods/tools/dump_mod_tables_ghidra.py")
    out.append("# Source: Guild Wars client image (Gw.wasm). DO NOT EDIT BY HAND.")
    out.append("#")
    out.append("# Label-table values are ETextStr string-table IDs. Resolve to display text via")
    out.append("#   from Py4GWCoreLib.native_src.internals import string_table")
    out.append("#   string_table.decode(bytes(<encoded-ref built from the id>))")
    out.append("# or map to your taxonomy labels directly by enum index.")
    out.append("")

    for name, base, count, stride in LABEL_TABLES:
        out.append("%s_TEXT_IDS = {" % name.upper())
        for i in range(count):
            tid = rd_u32(base + i * stride)
            out.append("    %d: 0x%X," % (i, tid))
        out.append("}")
        out.append("")

    out.append("# EItemType -> which upgrade slots the type accepts (from the caps bitmask).")
    out.append("EITEMTYPE_UPGRADE_CAPS = {")
    for t in range(CAPS_COUNT):
        caps = rd_u32(CAPS_BASE + t * CAPS_STRIDE)
        pre = bool((caps >> CAP_BIT_PREFIX) & 1)
        suf = bool((caps >> CAP_BIT_SUFFIX) & 1)
        inh = bool((caps >> CAP_BIT_INHERENT) & 1)
        out.append("    %d: {'raw': 0x%08X, 'prefix': %s, 'suffix': %s, 'inherent': %s}," % (
            t, caps, pre, suf, inh))
    out.append("}")
    out.append("")

    data = "\n".join(out)
    d = os.path.dirname(OUT_PATH)
    if d and not os.path.exists(d):
        os.makedirs(d)
    f = open(OUT_PATH, "w")
    try:
        f.write(data)
    finally:
        f.close()
    print("[dump_mod_tables] wrote %s (%d label tables + caps)" % (OUT_PATH, len(LABEL_TABLES)))


dump()
