"""
mods_upgrades -- upgrade name -> slot / variable-identifier / roll-range.
Migrated once from item_mods_src/upgrades.py (AST transcription of its class data);
plain static Python, no runtime generation, no JSON. Keyed by the folded upgrade name
(the ItemUpgrade member name), matching mods_core's upgrade-name resolution.
"""

# upgrade name -> Slot value (0 Inherent,1 Prefix,2 Suffix,3 Inscription,4 Rune,5 Insignia)
UPGRADE_SLOT: dict[str, int] = {
    "Adept":                           1,
    "AeromancerInsignia":              1,
    "AnchoritesInsignia":              1,
    "AptitudeNotAttitude":             3,
    "ArtificersInsignia":              1,
    "AssassinRuneOfMajorCriticalStrikes": 2,
    "AssassinRuneOfMajorDaggerMastery": 2,
    "AssassinRuneOfMajorDeadlyArts":   2,
    "AssassinRuneOfMajorShadowArts":   2,
    "AssassinRuneOfMinorCriticalStrikes": 2,
    "AssassinRuneOfMinorDaggerMastery": 2,
    "AssassinRuneOfMinorDeadlyArts":   2,
    "AssassinRuneOfMinorShadowArts":   2,
    "AssassinRuneOfSuperiorCriticalStrikes": 2,
    "AssassinRuneOfSuperiorDaggerMastery": 2,
    "AssassinRuneOfSuperiorDeadlyArts": 2,
    "AssassinRuneOfSuperiorShadowArts": 2,
    "Barbed":                          1,
    "BeJustAndFearNot":                3,
    "BeastmastersInsignia":            1,
    "BlessedInsignia":                 1,
    "BlightersInsignia":               1,
    "BloodstainedInsignia":            1,
    "BonelaceInsignia":                1,
    "BrawlersInsignia":                1,
    "BrawnOverBrains":                 3,
    "CastOutTheUnclean":               3,
    "CenturionsInsignia":              1,
    "Crippling":                       1,
    "Cruel":                           1,
    "DanceWithDeath":                  3,
    "Defensive":                       1,
    "DervishRuneOfMajorEarthPrayers":  2,
    "DervishRuneOfMajorMysticism":     2,
    "DervishRuneOfMajorScytheMastery": 2,
    "DervishRuneOfMajorWindPrayers":   2,
    "DervishRuneOfMinorEarthPrayers":  2,
    "DervishRuneOfMinorMysticism":     2,
    "DervishRuneOfMinorScytheMastery": 2,
    "DervishRuneOfMinorWindPrayers":   2,
    "DervishRuneOfSuperiorEarthPrayers": 2,
    "DervishRuneOfSuperiorMysticism":  2,
    "DervishRuneOfSuperiorScytheMastery": 2,
    "DervishRuneOfSuperiorWindPrayers": 2,
    "DisciplesInsignia":               1,
    "DontCallItAComeback":             3,
    "DontFearTheReaper":               3,
    "DontThinkTwice":                  3,
    "DownButNotOut":                   3,
    "DreadnoughtInsignia":             1,
    "EarthboundInsignia":              1,
    "Ebon":                            1,
    "ElementalistRuneOfMajorAirMagic": 2,
    "ElementalistRuneOfMajorEarthMagic": 2,
    "ElementalistRuneOfMajorEnergyStorage": 2,
    "ElementalistRuneOfMajorFireMagic": 2,
    "ElementalistRuneOfMajorWaterMagic": 2,
    "ElementalistRuneOfMinorAirMagic": 2,
    "ElementalistRuneOfMinorEarthMagic": 2,
    "ElementalistRuneOfMinorEnergyStorage": 2,
    "ElementalistRuneOfMinorFireMagic": 2,
    "ElementalistRuneOfMinorWaterMagic": 2,
    "ElementalistRuneOfSuperiorAirMagic": 2,
    "ElementalistRuneOfSuperiorEarthMagic": 2,
    "ElementalistRuneOfSuperiorEnergyStorage": 2,
    "ElementalistRuneOfSuperiorFireMagic": 2,
    "ElementalistRuneOfSuperiorWaterMagic": 2,
    "FaithIsMyShield":                 3,
    "FearCutsDeeper":                  3,
    "Fiery":                           1,
    "ForgetMeNot":                     3,
    "ForsakenInsignia":                1,
    "FrostboundInsignia":              1,
    "Furious":                         1,
    "GeomancerInsignia":               1,
    "GhostForgeInsignia":              1,
    "GuidedByFate":                    3,
    "HailToTheKing":                   3,
    "Hale":                            1,
    "HaleAndHearty":                   3,
    "HaveFaith":                       3,
    "Heavy":                           1,
    "HeraldsInsignia":                 1,
    "HydromancerInsignia":             1,
    "IAmSorrow":                       3,
    "ICanSeeClearlyNow":               3,
    "IHaveThePower":                   3,
    "Icy":                             1,
    "IgnoranceIsBliss":                3,
    "InfiltratorsInsignia":            1,
    "Insightful":                      1,
    "KnightsInsignia":                 1,
    "KnowingIsHalfTheBattle":          3,
    "LeafOnTheWind":                   3,
    "LetTheMemoryLiveAgain":           3,
    "LieutenantsInsignia":             1,
    "LifeIsPain":                      3,
    "LikeARollingStone":               3,
    "LiveForToday":                    3,
    "LuckOfTheDraw":                   3,
    "ManForAllSeasons":                3,
    "MasterOfMyDomain":                3,
    "MeasureForMeasure":               3,
    "MesmerRuneOfMajorDominationMagic": 2,
    "MesmerRuneOfMajorFastCasting":    2,
    "MesmerRuneOfMajorIllusionMagic":  2,
    "MesmerRuneOfMajorInspirationMagic": 2,
    "MesmerRuneOfMinorDominationMagic": 2,
    "MesmerRuneOfMinorFastCasting":    2,
    "MesmerRuneOfMinorIllusionMagic":  2,
    "MesmerRuneOfMinorInspirationMagic": 2,
    "MesmerRuneOfSuperiorDominationMagic": 2,
    "MesmerRuneOfSuperiorFastCasting": 2,
    "MesmerRuneOfSuperiorIllusionMagic": 2,
    "MesmerRuneOfSuperiorInspirationMagic": 2,
    "MightMakesRight":                 3,
    "MinionMastersInsignia":           1,
    "MonkRuneOfMajorDivineFavor":      2,
    "MonkRuneOfMajorHealingPrayers":   2,
    "MonkRuneOfMajorProtectionPrayers": 2,
    "MonkRuneOfMajorSmitingPrayers":   2,
    "MonkRuneOfMinorDivineFavor":      2,
    "MonkRuneOfMinorHealingPrayers":   2,
    "MonkRuneOfMinorProtectionPrayers": 2,
    "MonkRuneOfMinorSmitingPrayers":   2,
    "MonkRuneOfSuperiorDivineFavor":   2,
    "MonkRuneOfSuperiorHealingPrayers": 2,
    "MonkRuneOfSuperiorProtectionPrayers": 2,
    "MonkRuneOfSuperiorSmitingPrayers": 2,
    "MysticsInsignia":                 1,
    "NecromancerRuneOfMajorBloodMagic": 2,
    "NecromancerRuneOfMajorCurses":    2,
    "NecromancerRuneOfMajorDeathMagic": 2,
    "NecromancerRuneOfMajorSoulReaping": 2,
    "NecromancerRuneOfMinorBloodMagic": 2,
    "NecromancerRuneOfMinorCurses":    2,
    "NecromancerRuneOfMinorDeathMagic": 2,
    "NecromancerRuneOfMinorSoulReaping": 2,
    "NecromancerRuneOfSuperiorBloodMagic": 2,
    "NecromancerRuneOfSuperiorCurses": 2,
    "NecromancerRuneOfSuperiorDeathMagic": 2,
    "NecromancerRuneOfSuperiorSoulReaping": 2,
    "NightstalkersInsignia":           1,
    "NotTheFace":                      3,
    "NothingToFear":                   3,
    "OfAptitude":                      2,
    "OfAttribute":                     2,
    "OfAxeMastery":                    2,
    "OfDaggerMastery":                 2,
    "OfDefense":                       2,
    "OfDevotion":                      2,
    "OfEnchanting":                    2,
    "OfEndurance":                     2,
    "OfFortitude":                     2,
    "OfHammerMastery":                 2,
    "OfMarksmanship":                  2,
    "OfMastery":                       2,
    "OfMemory":                        2,
    "OfQuickening":                    2,
    "OfScytheMastery":                 2,
    "OfShelter":                       2,
    "OfSlaying":                       2,
    "OfSpearMastery":                  2,
    "OfSwiftness":                     2,
    "OfSwordsmanship":                 2,
    "OfTheProfession":                 2,
    "OfValor":                         2,
    "OfWarding":                       2,
    "OnlyTheStrongSurvive":            3,
    "ParagonRuneOfMajorCommand":       2,
    "ParagonRuneOfMajorLeadership":    2,
    "ParagonRuneOfMajorMotivation":    2,
    "ParagonRuneOfMajorSpearMastery":  2,
    "ParagonRuneOfMinorCommand":       2,
    "ParagonRuneOfMinorLeadership":    2,
    "ParagonRuneOfMinorMotivation":    2,
    "ParagonRuneOfMinorSpearMastery":  2,
    "ParagonRuneOfSuperiorCommand":    2,
    "ParagonRuneOfSuperiorLeadership": 2,
    "ParagonRuneOfSuperiorMotivation": 2,
    "ParagonRuneOfSuperiorSpearMastery": 2,
    "Poisonous":                       1,
    "PrismaticInsignia":               1,
    "ProdigysInsignia":                1,
    "PureOfHeart":                     3,
    "PyreboundInsignia":               1,
    "PyromancerInsignia":              1,
    "RadiantInsignia":                 1,
    "RangerRuneOfMajorBeastMastery":   2,
    "RangerRuneOfMajorExpertise":      2,
    "RangerRuneOfMajorMarksmanship":   2,
    "RangerRuneOfMajorWildernessSurvival": 2,
    "RangerRuneOfMinorBeastMastery":   2,
    "RangerRuneOfMinorExpertise":      2,
    "RangerRuneOfMinorMarksmanship":   2,
    "RangerRuneOfMinorWildernessSurvival": 2,
    "RangerRuneOfSuperiorBeastMastery": 2,
    "RangerRuneOfSuperiorExpertise":   2,
    "RangerRuneOfSuperiorMarksmanship": 2,
    "RangerRuneOfSuperiorWildernessSurvival": 2,
    "RidersOnTheStorm":                3,
    "RitualistRuneOfMajorChannelingMagic": 2,
    "RitualistRuneOfMajorCommuning":   2,
    "RitualistRuneOfMajorRestorationMagic": 2,
    "RitualistRuneOfMajorSpawningPower": 2,
    "RitualistRuneOfMinorChannelingMagic": 2,
    "RitualistRuneOfMinorCommuning":   2,
    "RitualistRuneOfMinorRestorationMagic": 2,
    "RitualistRuneOfMinorSpawningPower": 2,
    "RitualistRuneOfSuperiorChannelingMagic": 2,
    "RitualistRuneOfSuperiorCommuning": 2,
    "RitualistRuneOfSuperiorRestorationMagic": 2,
    "RitualistRuneOfSuperiorSpawningPower": 2,
    "RunForYourLife":                  3,
    "RuneOfAttunement":                2,
    "RuneOfClarity":                   2,
    "RuneOfMajorVigor":                2,
    "RuneOfMinorVigor":                2,
    "RuneOfMinorVigor2":               2,
    "RuneOfPurity":                    2,
    "RuneOfRecovery":                  2,
    "RuneOfRestoration":               2,
    "RuneOfSuperiorVigor":             2,
    "RuneOfVitae":                     2,
    "SaboteursInsignia":               1,
    "ScoutsInsignia":                  1,
    "SeizeTheDay":                     3,
    "SentinelsInsignia":               1,
    "SentrysInsignia":                 1,
    "SerenityNow":                     3,
    "ShamansInsignia":                 1,
    "ShelteredByFaith":                3,
    "Shocking":                        1,
    "ShowMeTheMoney":                  3,
    "Silencing":                       1,
    "SleepNowInTheFire":               3,
    "SoundnessOfMind":                 3,
    "StalwartInsignia":                1,
    "StonefistInsignia":               1,
    "StormboundInsignia":              1,
    "StrengthAndHonor":                3,
    "StrengthOfBody":                  3,
    "Sundering":                       1,
    "SurvivalOfTheFittest":            3,
    "SurvivorInsignia":                1,
    "Swift":                           1,
    "SwiftAsTheWind":                  3,
    "TheRiddleOfSteel":                3,
    "ThroughThickAndThin":             3,
    "ToThePain":                       3,
    "TooMuchInformation":              3,
    "TormentorsInsignia":              1,
    "UndertakersInsignia":             1,
    "VampiricMajor":                   1,
    "VampiricMinor":                   1,
    "VanguardsInsignia":               1,
    "VengeanceIsMine":                 3,
    "VirtuososInsignia":               1,
    "WanderersInsignia":               1,
    "WarriorRuneOfMajorAbsorption":    2,
    "WarriorRuneOfMajorAxeMastery":    2,
    "WarriorRuneOfMajorHammerMastery": 2,
    "WarriorRuneOfMajorStrength":      2,
    "WarriorRuneOfMajorSwordsmanship": 2,
    "WarriorRuneOfMajorTactics":       2,
    "WarriorRuneOfMinorAbsorption":    2,
    "WarriorRuneOfMinorAxeMastery":    2,
    "WarriorRuneOfMinorHammerMastery": 2,
    "WarriorRuneOfMinorStrength":      2,
    "WarriorRuneOfMinorSwordsmanship": 2,
    "WarriorRuneOfMinorTactics":       2,
    "WarriorRuneOfSuperiorAbsorption": 2,
    "WarriorRuneOfSuperiorAxeMastery": 2,
    "WarriorRuneOfSuperiorHammerMastery": 2,
    "WarriorRuneOfSuperiorStrength":   2,
    "WarriorRuneOfSuperiorSwordsmanship": 2,
    "WarriorRuneOfSuperiorTactics":    2,
    "WindwalkerInsignia":              1,
    "Zealous":                         1,
}

# upgrade name -> variable effect identifier (stripped ModifierIdentifier int)
UPGRADE_VAR: dict[str, int] = {
    "Adept":                           0x280,
    "AeromancerInsignia":              0x212,
    "AptitudeNotAttitude":             0x280,
    "Barbed":                          0x246,
    "BeJustAndFearNot":                0x21C,
    "BrawnOverBrains":                 0x223,
    "CastOutTheUnclean":               0x285,
    "Crippling":                       0x246,
    "Cruel":                           0x246,
    "DanceWithDeath":                  0x22A,
    "Defensive":                       0x210,
    "DontCallItAComeback":             0x231,
    "DontFearTheReaper":               0x229,
    "DontThinkTwice":                  0x220,
    "DownButNotOut":                   0x21B,
    "Ebon":                            0x24B,
    "FaithIsMyShield":                 0x219,
    "FearCutsDeeper":                  0x285,
    "Fiery":                           0x24B,
    "ForgetMeNot":                     0x282,
    "Furious":                         0x23B,
    "GeomancerInsignia":               0x212,
    "GuidedByFate":                    0x226,
    "HailToTheKing":                   0x21A,
    "Hale":                            0x234,
    "HaleAndHearty":                   0x230,
    "HaveFaith":                       0x22F,
    "Heavy":                           0x246,
    "HydromancerInsignia":             0x212,
    "IAmSorrow":                       0x232,
    "ICanSeeClearlyNow":               0x285,
    "IHaveThePower":                   0x22D,
    "Icy":                             0x24B,
    "IgnoranceIsBliss":                0x210,
    "Insightful":                      0x22D,
    "KnowingIsHalfTheBattle":          0x218,
    "LeafOnTheWind":                   0x211,
    "LetTheMemoryLiveAgain":           0x23A,
    "LifeIsPain":                      0x210,
    "LikeARollingStone":               0x211,
    "LiveForToday":                    0x22D,
    "LuckOfTheDraw":                   0x207,
    "ManForAllSeasons":                0x212,
    "MasterOfMyDomain":                0x283,
    "MeasureForMeasure":               0x260,
    "MightMakesRight":                 0x217,
    "NotTheFace":                      0x211,
    "NothingToFear":                   0x209,
    "OfAptitude":                      0x280,
    "OfAxeMastery":                    0x241,
    "OfDaggerMastery":                 0x241,
    "OfDefense":                       0x210,
    "OfDevotion":                      0x236,
    "OfEnchanting":                    0x22B,
    "OfEndurance":                     0x238,
    "OfFortitude":                     0x234,
    "OfHammerMastery":                 0x241,
    "OfMarksmanship":                  0x241,
    "OfMastery":                       0x283,
    "OfMemory":                        0x282,
    "OfQuickening":                    0x23A,
    "OfScytheMastery":                 0x241,
    "OfShelter":                       0x215,
    "OfSpearMastery":                  0x241,
    "OfSwiftness":                     0x220,
    "OfSwordsmanship":                 0x241,
    "OfValor":                         0x237,
    "OfWarding":                       0x212,
    "OnlyTheStrongSurvive":            0x285,
    "Poisonous":                       0x246,
    "PureOfHeart":                     0x285,
    "PyromancerInsignia":              0x212,
    "RidersOnTheStorm":                0x211,
    "RunForYourLife":                  0x20A,
    "RuneOfClarity":                   0x277,
    "RuneOfPurity":                    0x277,
    "RuneOfRecovery":                  0x277,
    "RuneOfRestoration":               0x277,
    "RuneOfVitae":                     0x234,
    "SeizeTheDay":                     0x22D,
    "SerenityNow":                     0x23A,
    "ShelteredByFaith":                0x208,
    "Shocking":                        0x24B,
    "ShowMeTheMoney":                  0x25F,
    "Silencing":                       0x246,
    "SleepNowInTheFire":               0x211,
    "SoundnessOfMind":                 0x285,
    "StalwartInsignia":                0x215,
    "StrengthAndHonor":                0x227,
    "StrengthOfBody":                  0x285,
    "Sundering":                       0x23F,
    "SurvivalOfTheFittest":            0x215,
    "Swift":                           0x220,
    "SwiftAsTheWind":                  0x285,
    "TheRiddleOfSteel":                0x211,
    "ThroughThickAndThin":             0x211,
    "ToThePain":                       0x223,
    "TooMuchInformation":              0x225,
    "VampiricMajor":                   0x20E,
    "VampiricMinor":                   0x20E,
    "VengeanceIsMine":                 0x228,
    "Zealous":                         0x251,
}

# upgrade name -> (min, max) roll range of its variable value (for IsMaxed)
UPGRADE_RANGE: dict[str, tuple[int, int]] = {
    "Adept":                           (10, 20),
    "AptitudeNotAttitude":             (10, 20),
    "BeJustAndFearNot":                (5, 10),
    "BrawnOverBrains":                 (14, 15),
    "DanceWithDeath":                  (10, 15),
    "Defensive":                       (4, 5),
    "DontCallItAComeback":             (5, 7),
    "DontFearTheReaper":               (10, 20),
    "DontThinkTwice":                  (5, 10),
    "DownButNotOut":                   (5, 10),
    "FaithIsMyShield":                 (4, 5),
    "ForgetMeNot":                     (10, 20),
    "Furious":                         (2, 10),
    "GuidedByFate":                    (10, 15),
    "HailToTheKing":                   (4, 5),
    "Hale":                            (10, 30),
    "HaleAndHearty":                   (4, 5),
    "HaveFaith":                       (4, 5),
    "IAmSorrow":                       (5, 7),
    "IgnoranceIsBliss":                (4, 5),
    "Insightful":                      (1, 5),
    "LeafOnTheWind":                   (5, 10),
    "LetTheMemoryLiveAgain":           (5, 10),
    "LifeIsPain":                      (4, 5),
    "LikeARollingStone":               (5, 10),
    "LiveForToday":                    (10, 15),
    "LuckOfTheDraw":                   (11, 20),
    "ManForAllSeasons":                (4, 5),
    "MasterOfMyDomain":                (11, 20),
    "MightMakesRight":                 (4, 5),
    "NotTheFace":                      (5, 10),
    "NothingToFear":                   (1, 3),
    "OfAptitude":                      (10, 20),
    "OfDefense":                       (4, 5),
    "OfDevotion":                      (30, 45),
    "OfEnchanting":                    (10, 20),
    "OfEndurance":                     (30, 45),
    "OfFortitude":                     (10, 30),
    "OfMastery":                       (10, 20),
    "OfMemory":                        (10, 20),
    "OfQuickening":                    (5, 10),
    "OfShelter":                       (4, 7),
    "OfSwiftness":                     (5, 10),
    "OfValor":                         (45, 60),
    "OfWarding":                       (4, 7),
    "RidersOnTheStorm":                (5, 10),
    "RunForYourLife":                  (1, 2),
    "SeizeTheDay":                     (10, 15),
    "SerenityNow":                     (7, 10),
    "ShelteredByFaith":                (1, 2),
    "SleepNowInTheFire":               (5, 10),
    "StrengthAndHonor":                (10, 15),
    "Sundering":                       (10, 20),
    "SurvivalOfTheFittest":            (4, 5),
    "Swift":                           (5, 10),
    "TheRiddleOfSteel":                (5, 10),
    "ThroughThickAndThin":             (5, 10),
    "ToThePain":                       (14, 15),
    "TooMuchInformation":              (10, 15),
    "VengeanceIsMine":                 (10, 20),
}

# upgrade_id -> effect description (game 390-table, FULL/untruncated). Single-desc upgrades
# only (runes/insignias whose effect is intrinsic). backslash-n = a line-break placeholder.
UPGRADE_DESC: dict[int, str] = {
    0x81: "Cold Damage",
    0x82: "Earth Damage",
    0x83: "Lightning Damage",
    0x84: "Fire Damage",
    0x85: "Cold Damage",
    0x86: "Earth Damage",
    0x87: "Lightning Damage",
    0x88: "Fire Damage",
    0x89: "Cold Damage",
    0x8A: "Earth Damage",
    0x8B: "Lightning Damage",
    0x8C: "Fire Damage",
    0x8D: "Cold Damage",
    0x8E: "Earth Damage",
    0x8F: "Lightning Damage",
    0x90: "Fire Damage",
    0x91: "Armor +4",
    0x92: "Lengthens Bleeding duration on foes by 33% \\n (Stacking)",
    0x93: "Lengthens Bleeding duration on foes by 33% \\n (Stacking)",
    0x94: "Lengthens Crippled duration on foes by 33% \\n (Stacking)",
    0x95: "Lengthens Crippled duration on foes by 33% \\n (Stacking)",
    0x96: "Lengthens Deep Wound duration on foes by 33% \\n (Stacking)",
    0x97: "Lengthens Deep Wound duration on foes by 33% \\n (Stacking)",
    0x98: "Lengthens Deep Wound duration on foes by 33% \\n (Stacking)",
    0x99: "Double adrenaline gain \\n (Chance: 5%)",
    0x9A: "Double adrenaline gain \\n (Chance: 5%)",
    0x9B: "Double adrenaline gain \\n (Chance: 5%)",
    0x9C: "Energy +1",
    0x9D: "Health +10",
    0x9E: "Lengthens Poison duration on foes by 33% \\n (Stacking)",
    0x9F: "Lengthens Poison duration on foes by 33% \\n (Stacking)",
    0xA0: "Lengthens Poison duration on foes by 33% \\n (Stacking)",
    0xA1: "Lengthens Weakness duration on foes by 33% \\n (Stacking)",
    0xA2: "Lengthens Weakness duration on foes by 33% \\n (Stacking)",
    0xA3: "Energy gain on hit: 1 \\n Energy regeneration -1",
    0xA4: "Energy gain on hit: 1 \\n Energy regeneration -1",
    0xA5: "Energy gain on hit: 1 \\n Energy regeneration -1",
    0xA6: "Energy gain on hit: 1 \\n Energy regeneration -1",
    0xA7: "Life Draining: 1 \\n Health regeneration -1",
    0xA8: "Life Draining: 1 \\n Health regeneration -1",
    0xA9: "Life Draining: 1 \\n Health regeneration -1",
    0xAA: "Life Draining: 1 \\n Health regeneration -1",
    0xAB: "Armor penetration +20% \\n (Chance: 10%)",
    0xAC: "Armor penetration +20% \\n (Chance: 10%)",
    0xAD: "Armor penetration +20% \\n (Chance: 10%)",
    0xAE: "Armor penetration +20% \\n (Chance: 10%)",
    0xC1: "Reduces physical damage by 1 \\n (Non-stacking)",
    0xC2: "Health +30 \\n (Non-stacking)",
    0xC5: "Armor +4",
    0xC6: "Armor +4",
    0xC7: "Armor +4 \\n (vs. elemental damage)",
    0xC8: "Armor +4 \\n (vs. elemental damage)",
    0xC9: "Armor +4 \\n (vs. elemental damage)",
    0xCA: "Armor +4 \\n (vs. elemental damage)",
    0xCB: "Armor +4 \\n (vs. elemental damage)",
    0xCC: "Armor +4",
    0xCD: "Armor +4 \\n (vs. physical damage)",
    0xCE: "Armor +4 \\n (vs. physical damage)",
    0xCF: "Armor +4 \\n (vs. physical damage)",
    0xD0: "Armor +4 \\n (vs. physical damage)",
    0xD1: "Armor +4 \\n (vs. physical damage)",
    0xD2: "Armor +4",
    0xD3: "Armor +4",
    0xD9: "Health +20",
    0xDA: "Health +20",
    0xDB: "Health +20",
    0xDC: "Health +20",
    0xDD: "Health +20",
    0xDE: "Enchantments last 10% longer",
    0xDF: "Enchantments last 10% longer",
    0xE0: "Enchantments last 10% longer",
    0xE1: "Enchantments last 10% longer",
    0xE2: "Enchantments last 10% longer",
    0xE8: "Axe Mastery +1 \\n (0% chance while using skills)",
    0xE9: "Marksmanship +1 \\n (0% chance while using skills)",
    0xEA: "Hammer Mastery +1 \\n (0% chance while using skills)",
    0xEB: "Swordsmanship +1 \\n (0% chance while using skills)",
    0xFC: "Reduces physical damage by 1 \\n (Non-stacking)",
    0xFD: "Reduces physical damage by 2 \\n (Non-stacking)",
    0xFE: "Reduces physical damage by 3 \\n (Non-stacking)",
    0xFF: "Health +30 \\n (Non-stacking)",
    0x100: "Health +41 \\n (Non-stacking)",
    0x101: "Health +50 \\n (Non-stacking)",
    0x12E: "Cold Damage",
    0x12F: "Earth Damage",
    0x130: "Fire Damage",
    0x131: "Lightning Damage",
    0x132: "Energy gain on hit: 1 \\n Energy regeneration -1",
    0x133: "Life Draining: 1 \\n Health regeneration -1",
    0x134: "Armor penetration +20% \\n (Chance: 10%)",
    0x135: "Lengthens Bleeding duration on foes by 33% \\n (Stacking)",
    0x136: "Lengthens Crippled duration on foes by 33% \\n (Stacking)",
    0x137: "Lengthens Deep Wound duration on foes by 33% \\n (Stacking)",
    0x138: "Lengthens Poison duration on foes by 33% \\n (Stacking)",
    0x139: "Lengthens Dazed duration on foes by 33% \\n (Stacking)",
    0x13A: "Double adrenaline gain \\n (Chance: 5%)",
    0x141: "Armor +4",
    0x142: "Armor +4 \\n (vs. elemental damage)",
    0x143: "Armor +4 \\n (vs. physical damage)",
    0x144: "Enchantments last 10% longer",
    0x145: "Health +20",
    0x146: "Dagger Mastery +1 \\n (0% chance while using skills)",
    0x147: "Lengthens Bleeding duration on foes by 33% \\n (Stacking)",
    0x148: "Lengthens Crippled duration on foes by 33% \\n (Stacking)",
    0x149: "Lengthens Dazed duration on foes by 33% \\n (Stacking)",
    0x151: "Health +45 \\n (while Hexed)",
    0x152: "Health +30 \\n (while in a Stance)",
    0x153: "Item's attribute +1 \\n (Chance: 10%)",
    0x154: "Health +30 \\n (while Enchanted)",
    0x155: "Health +45 \\n (while Hexed)",
    0x156: "Health +30 \\n (while in a Stance)",
    0x15C: "Energy +5",
    0x15E: "Halves skill recharge of spells \\n (Chance: 5%)",
    0x15F: "Halves skill recharge on spells of item's attribute \\n (Chance: 10%)",
    0x160: "Halves skill recharge of spells \\n (Chance: 5%)",
    0x161: "Health +10",
    0x162: "Health +30 \\n (while Enchanted)",
    0x163: "Damage +10% \\n (vs. Hexed foes)",
    0x164: "Damage +10% \\n (while Enchanted)",
    0x165: "Damage +10% \\n (while Health is above 50%)",
    0x166: "Damage +10% \\n (while Health is below 50%)",
    0x167: "Damage +10% \\n (while Hexed)",
    0x168: "Damage +10% \\n (while in a Stance)",
    0x169: "Damage +10% \\n Energy -5",
    0x16A: "Damage +10% \\n Armor -10 \\n (while attacking)",
    0x16B: "Cold Damage",
    0x16C: "Earth Damage",
    0x16D: "Fire Damage",
    0x16E: "Lightning Damage",
    0x16F: "Energy gain on hit: 1 \\n Energy regeneration -1",
    0x170: "Energy gain on hit: 1 \\n Energy regeneration -1",
    0x171: "Life Draining: 1 \\n Health regeneration -1",
    0x172: "Life Draining: 1 \\n Health regeneration -1",
    0x173: "Armor penetration +20% \\n (Chance: 20%)",
    0x174: "Lengthens Bleeding duration on foes by 33% \\n (Stacking)",
    0x175: "Lengthens Crippled duration on foes by 33% \\n (Stacking)",
    0x176: "Lengthens Deep Wound duration on foes by 33% \\n (Stacking)",
    0x177: "Lengthens Poison duration on foes by 33% \\n (Stacking)",
    0x178: "Lengthens Weakness duration on foes by 33% \\n (Stacking)",
    0x179: "Double adrenaline gain \\n (Chance: 5%)",
    0x17A: "Armor penetration +20% \\n (Chance: 20%)",
    0x17B: "Lengthens Bleeding duration on foes by 33% \\n (Stacking)",
    0x17C: "Lengthens Crippled duration on foes by 33% \\n (Stacking)",
    0x17D: "Lengthens Deep Wound duration on foes by 33% \\n (Stacking)",
    0x17E: "Lengthens Poison duration on foes by 33% \\n (Stacking)",
    0x17F: "Lengthens Dazed duration on foes by 33% \\n (Stacking)",
    0x180: "Double adrenaline gain \\n (Chance: 5%)",
    0x181: "Lengthens Weakness duration on foes by 33% \\n (Stacking)",
    0x188: "Armor +4",
    0x189: "Armor +4 \\n (vs. elemental damage)",
    0x18A: "Armor +4 \\n (vs. physical damage)",
    0x18B: "Enchantments last 10% longer",
    0x18C: "Health +20",
    0x18D: "Scythe Mastery +1 \\n (0% chance while using skills)",
    0x18E: "Armor +4",
    0x18F: "Armor +4 \\n (vs. elemental damage)",
    0x190: "Armor +4 \\n (vs. physical damage)",
    0x191: "Enchantments last 10% longer",
    0x192: "Health +20",
    0x193: "Spear Mastery +1 \\n (0% chance while using skills)",
    0x1B6: "Armor +4 \\n Energy -5",
    0x1B7: "Armor +4 \\n Health -20",
    0x1B8: "Armor +4 \\n (vs. elemental damage)",
    0x1B9: "Armor +4 \\n (vs. physical damage)",
    0x1BA: "Armor +4 \\n (while attacking)",
    0x1BB: "Armor +4 \\n (while casting)",
    0x1BC: "Armor +4 \\n (while Enchanted)",
    0x1BD: "Armor +5 \\n (while Health is below 50%)",
    0x1BE: "Armor +4 \\n (while Health is above 50%)",
    0x1BF: "Armor +5 \\n (while Hexed)",
    0x1C0: "Energy +10 \\n Energy regeneration -1",
    0x1C1: "Halves skill recharge of spells \\n (Chance: 5%)",
    0x1C2: "Halves skill recharge on spells of item's attribute \\n (Chance: 10%)",
    0x1C3: "Armor +5 \\n (vs. Blunt damage)",
    0x1C4: "Armor +5 \\n (vs. Cold damage)",
    0x1C5: "Armor +5 \\n (vs. Earth damage)",
    0x1C6: "Armor +5 \\n (vs. Lightning damage)",
    0x1C7: "Armor +5 \\n (vs. Fire damage)",
    0x1C8: "Armor +5 \\n (vs. Piercing damage)",
    0x1C9: "Armor +5 \\n (vs. Slashing damage)",
    0x1CA: "Reduces Bleeding duration on you by 20% \\n (Stacking)",
    0x1CB: "Reduces Blind duration on you by 20% \\n (Stacking)",
    0x1CC: "Reduces Crippled duration on you by 20% \\n (Stacking)",
    0x1CD: "Reduces Deep Wound duration on you by 20% \\n (Stacking)",
    0x1CE: "Reduces Disease duration on you by 20% \\n (Stacking)",
    0x1CF: "Reduces Poison duration on you by 20% \\n (Stacking)",
    0x1D0: "Reduces Dazed duration on you by 20% \\n (Stacking)",
    0x1D1: "Reduces Weakness duration on you by 20% \\n (Stacking)",
    0x1D2: "Received physical damage -5 \\n (Chance: 10%)",
    0x1D3: "Received physical damage -1 \\n (while Enchanted)",
    0x1D4: "Received physical damage -1 \\n (while Hexed)",
    0x1D5: "Received physical damage -1 \\n (while in a Stance)",
    0x1D6: "Item's attribute +1 \\n (Chance: 10%)",
    0x1D7: "Halves casting time on spells of item's attribute \\n (Chance: 10%)",
    0x1D8: "Energy +10 \\n Energy regeneration -1",
    0x1D9: "Energy +4 \\n (while Enchanted)",
    0x1DA: "Energy +4 \\n (while Health is above 50%)",
    0x1DB: "Energy +5 \\n (while Health is below 50%)",
    0x1DC: "Energy +5 \\n (while Hexed)",
    0x1DD: "Halves casting time of spells \\n (Chance: 5%)",
    0x1DE: "Armor +10 \\n (vs. physical damage) \\n Armor +10 \\n (vs. Blunt damage)",
    0x1DF: "Armor +10 \\n (vs. physical damage) \\n Armor +10 \\n (vs. Piercing damage)",
    0x1E0: "Armor +10 \\n (vs. physical damage) \\n Armor +10 \\n (vs. Slashing damage)",
    0x1E1: "Armor +15 \\n (while attacking)",
    0x1E2: "Armor +3 \\n (for each equipped Signet)",
    0x1E3: "Armor +5 \\n (while recharging 1 or more skills) \\n Armor +5 \\n (while recharging 3 or more skills) \\n Armor +5 \\n (while recharging 5 or more skills)",
    0x1E4: "Armor +15 \\n (while activating skills)",
    0x1E5: "Energy +3 \\n (on chest armor) \\n Energy +2 \\n (on leg armor) \\n Energy +1 \\n (on other armor)",
    0x1E6: "Health +15 \\n (on chest armor) \\n Health +10 \\n (on leg armor) \\n Health +5 \\n (on other armor)",
    0x1E7: "Armor +10 \\n (vs. physical damage)",
    0x1E8: "Armor +10 \\n (while attacking)",
    0x1E9: "Armor +10 \\n (while affected by an Enchantment Spell)",
    0x1EA: "Armor +10 \\n (while holding an item)",
    0x1EB: "Armor +10 \\n (while in a Stance)",
    0x1EC: "Holy damage you receive increased by 6 \\n (on chest armor) \\n Holy damage you receive increased by 4 \\n (on leg armor) \\n Holy damage you receive increased by 2 \\n (on other armor) \\n Armor +10",
    0x1ED: "Armor +5 \\n (while Health is below 80%) \\n Armor +5 \\n (while Health is below 60%) \\n Armor +5 \\n (while Health is below 40%) \\n Armor +5 \\n (while Health is below 20%)",
    0x1EE: "Armor +15 \\n (vs. Piercing damage)",
    0x1EF: "Armor +5 \\n (while you control 1 or more minions) \\n Armor +5 \\n (while you control 3 or more minions) \\n Armor +5 \\n (while you control 5 or more minions)",
    0x1F0: "Armor +20 \\n (while affected by a Hex Spell)",
    0x1F1: "Armor +5 \\n (Requires 9 Air Magic) \\n Armor +5 \\n (Requires 9 Earth Magic) \\n Armor +5 \\n (Requires 9 Fire Magic) \\n Armor +5 \\n (Requires 9 Water Magic)",
    0x1F2: "Armor +10 \\n (vs. elemental damage) \\n Armor +10 \\n (vs. Cold damage)",
    0x1F3: "Armor +10 \\n (vs. elemental damage) \\n Armor +10 \\n (vs. Earth damage)",
    0x1F4: "Armor +10 \\n (vs. elemental damage) \\n Armor +10 \\n (vs. Fire damage)",
    0x1F5: "Armor +10 \\n (vs. elemental damage) \\n Armor +10 \\n (vs. Lightning damage)",
    0x1F6: "Armor +10 \\n (vs. elemental damage)",
    0x1F7: "Armor +15 \\n (while affected by a Condition)",
    0x1F8: "Armor +5 \\n (while recharging 1 or more skills) \\n Armor +5 \\n (while recharging 3 or more skills) \\n Armor +5 \\n (while recharging 5 or more skills)",
    0x1F9: "Received physical damage -3",
    0x1FA: "Armor +10 \\n (vs. elemental damage)",
    0x1FB: "Armor +20 \\n (Requires 13 Strength), \\n vs. elemental damage",
    0x1FC: "Armor +15 \\n (vs. Cold damage)",
    0x1FD: "Armor +15 \\n (vs. Earth damage)",
    0x1FE: "Armor +15 \\n (vs. Fire damage)",
    0x1FF: "Armor +15 \\n (vs. Lightning damage)",
    0x200: "Armor +10 \\n (while your pet is alive)",
    0x201: "Armor +10 \\n (while using a Preparation)",
    0x202: "Armor +5 \\n (while affected by or more Enchantment Spell) \\n Armor +5 \\n (while affected by 2 or more Enchantment Spells) \\n Armor +5 \\n (while affected by 3 or more Enchantment Spells) \\n Armor +5 \\n (while affected by 4 or more Enchantment Spells)",
    0x203: "Armor +10 \\n (while not affected by an Enchantment Spell)",
    0x204: "Armor +5 \\n (while you control 1 or more Spirits) \\n Armor +5 \\n (while you control 2 or more Spirits) \\n Armor +5 \\n (while you control 3 or more Spirits)",
    0x205: "Armor +15 \\n (while affected by a Weapon Spell)",
    0x206: "Armor +15 \\n (while activating skills)",
    0x207: "Armor +10 \\n (while affected by a Shout, Echo, or Chant)",
    0x208: "Reduces hex durations on you by 20% and damage dealt by you by 5% \\n (Non-stacking) \\n Armor -20",
    0x209: "Increases knockdown time of foes by 1 second. (Maximum: 3 seconds) \\n (Non-stacking)",
    0x20A: "Reduces casting time of spells that exploit corpses by 25% \\n (Non-stacking)",
    0x20B: "Fire Damage",
    0x20C: "Lightning Damage",
    0x20D: "Cold Damage",
    0x20E: "Earth Damage",
    0x20F: "Halves casting time of spells \\n (Chance: 5%)",
    0x210: "Halves casting time on spells of item's attribute \\n (Chance: 10%)",
    0x211: "Energy +2",
    0x212: "Health +10",
    0x213: "Reduces Dazed duration on you by 20% \\n (Non-stacking) \\n Reduces Deep Wound duration on you by 20% \\n (Non-stacking)",
    0x214: "Reduces Bleeding duration on you by 20% \\n (Non-stacking) \\n Reduces Crippled duration on you by 20% \\n (Non-stacking)",
    0x215: "Reduces Blind duration on you by 20% \\n (Non-stacking) \\n Reduces Weakness duration on you by 20% \\n (Non-stacking)",
    0x216: "Reduces Disease duration on you by 20% \\n (Non-stacking) \\n Reduces Poison duration on you by 20% \\n (Non-stacking)",
    0x217: "Halves casting time on spells of item's attribute \\n (Chance: 10%)",
    0x218: "Health +10",
    0x219: "Health +30 \\n (while Enchanted)",
    0x21A: "Health +45 \\n (while Hexed)",
    0x21B: "Health +30 \\n (while in a Stance)",
    0x21C: "Halves casting time of spells \\n (Chance: 5%)",
}
