# PyAgent stub — Reforged Native surface (2026-07-06)
# Matches agent_bindings.cpp. PyAgent class + Profession class + module-level free functions.

from typing import List, Tuple
from enum import IntEnum

class ProfessionType(IntEnum):
    None_: int = 0
    Warrior: int
    Ranger: int
    Monk: int
    Necromancer: int
    Mesmer: int
    Elementalist: int
    Assassin: int
    Ritualist: int
    Paragon: int
    Dervish: int

class Profession:
    def __init__(self, prof: int | str = 0) -> None: ...
    def GetName(self) -> str: ...
    def ToInt(self) -> int: ...
    def Set(self, prof: int) -> None: ...
    def Get(self) -> ProfessionType: ...

class PyAgent:
    def __init__(self, agent_id: int = 0) -> None: ...
    def GetContext(self) -> None: ...
    def GetAgentID(self) -> int: ...
    def GetPlayerNumber(self) -> int: ...
    def GetName(self) -> str: ...
    def GetPrimary(self) -> int: ...
    def GetSecondary(self) -> int: ...
    def GetLevel(self) -> int: ...
    def GetHP(self) -> float: ...
    def GetRotation(self) -> float: ...
    def GetPos(self) -> Tuple[float, float, float]: ...
    def GetIsLiving(self) -> bool: ...
    def GetIsDead(self) -> bool: ...
    def GetIsMoving(self) -> bool: ...
    def GetIsAttacking(self) -> bool: ...
    def GetIsKnockedDown(self) -> bool: ...
    def GetIsCasting(self) -> bool: ...
    def GetAllegiance(self) -> int: ...
    def GetIsGadget(self) -> bool: ...
    def GetIsItem(self) -> bool: ...

    @staticmethod
    def GetTargetId() -> int: ...
    @staticmethod
    def GetControlledCharacterId() -> int: ...
    @staticmethod
    def GetObservingId() -> int: ...

# ── Module-level free functions (use these instead of PyAgent static methods where needed) ──
def send_dialog(dialog_id: int) -> bool: ...
def get_observing_id() -> int: ...
def get_controlled_character_id() -> int: ...
def get_target_id() -> int: ...
def get_amount_of_players_in_instance() -> int: ...
def is_observing() -> bool: ...
def change_target(agent_id: int) -> bool: ...
def move(x: float, y: float, zplane: int = 0) -> bool: ...
def interact_agent(agent_id: int, call_target: bool = False) -> bool: ...
def call_target(agent_id: int) -> bool: ...
def get_player_name_by_login_number(login_number: int) -> str: ...
def get_agent_id_by_login_number(login_number: int) -> int: ...
def get_hero_agent_id(hero_index: int) -> int: ...
def get_agent_enc_name(agent_id: int) -> List[int]:
    """Returns raw UTF-16LE bytes as list[int]."""
    ...
def get_agent_is_targettable(agent_id: int) -> bool: ...
