# PyCamera stub — Reforged Native surface (2026-07-06)
# Matches camera_bindings.cpp. PyCamera class + Point3D helper.

from typing import Tuple

class Point3D:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...

class PyCamera:
    look_at_agent_id: int
    yaw: float
    pitch: float
    camera_zoom: float
    max_distance: float
    yaw_right_click: float
    yaw_right_click2: float
    pitch_right_click: float
    distance2: float
    acceleration_constant: float
    field_of_view: float
    field_of_view2: float
    h0024: Tuple[float, ...]
    h0070: Tuple[float, ...]
    position: Point3D
    camera_pos_to_go: Point3D
    cam_pos_inverted: Point3D
    cam_pos_inverted_to_go: Point3D
    look_at_target: Point3D
    look_at_to_go: Point3D

    def __init__(self) -> None: ...
    def GetContext(self) -> None: ...
    def SetYaw(self, _yaw: float) -> None: ...
    def SetPitch(self, _pitch: float) -> None: ...
    def SetMaxDist(self, dist: float) -> None: ...
    def SetFieldOfView(self, fov: float) -> None: ...
    def UnlockCam(self, unlock: bool) -> None: ...
    def GetCameraUnlock(self) -> bool: ...
    def ForwardMovement(self, amount: float, true_forward: bool) -> None: ...
    def VerticalMovement(self, amount: float) -> None: ...
    def SideMovement(self, amount: float) -> None: ...
    def RotateMovement(self, angle: float) -> None: ...
    def ComputeCameraPos(self) -> Point3D: ...
    def UpdateCameraPos(self) -> None: ...
    def SetCameraPos(self, x: float, y: float, z: float) -> None: ...
    def SetLookAtTarget(self, x: float, y: float, z: float) -> None: ...
    def SetFog(self, fog: bool) -> None: ...

# ── Module-level free functions ──
def forward_movement(amount: float, true_forward: bool = False) -> None: ...
def vertical_movement(amount: float) -> None: ...
def rotate_movement(angle: float) -> None: ...
def side_movement(amount: float) -> None: ...
def set_max_dist(dist: float = 900.0) -> None: ...
def set_field_of_view(fov: float) -> None: ...
def compute_cam_pos(dist: float = 0.0) -> Tuple[float, float, float]: ...
def update_camera_pos() -> None: ...
def get_field_of_view() -> float: ...
def get_yaw() -> float: ...
def unlock_cam(flag: bool) -> None: ...
def get_camera_unlock() -> bool: ...
def set_fog(flag: bool) -> None: ...
def get_context_ptr() -> int: ...
