# PyDXOverlay stub — Reforged Native surface (2026-07-06)
# Replaces legacy Py2DRenderer. Provides 2D and 3D drawing over the DX9 device.
# Matches dx_overlay_bindings.cpp.

from typing import List, Tuple

class DXOverlay:
    def __init__(self) -> None: ...

    def set_primitives(self, primitives: int, draw_color: int = 0xFFFFFFFF) -> None: ...
    def build_pathing_trapezoid_geometry(self, color: int = 0xFF00FF00) -> None: ...
    def inverse_rendering(self, enabled: bool) -> None: ...

    def set_world_zoom_x(self, zoom: float) -> None: ...
    def set_world_zoom_y(self, zoom: float) -> None: ...
    def set_world_pan(self, x: float, y: float) -> None: ...
    def set_world_rotation(self, r: float) -> None: ...
    def set_world_space(self, enabled: bool) -> None: ...
    def set_world_scale(self, scale: float) -> None: ...

    def set_screen_offset(self, x: float, y: float) -> None: ...
    def set_screen_zoom_x(self, zoom: float) -> None: ...
    def set_screen_zoom_y(self, zoom: float) -> None: ...
    def set_screen_rotation(self, r: float) -> None: ...

    def set_circular_mask(self, enabled: bool) -> None: ...
    def set_circular_mask_radius(self, radius: float) -> None: ...
    def set_circular_mask_center(self, x: float, y: float) -> None: ...

    def set_rectangle_mask(self, enabled: bool) -> None: ...
    def set_rectangle_mask_bounds(self, x: float, y: float, width: float, height: float) -> None: ...

    def render(self) -> None: ...

    # 2D drawing
    def DrawLine(self, _from: Tuple[float, float], to: Tuple[float, float], color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawTriangle(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawTriangleFilled(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], color: int = 0xFFFFFFFF) -> None: ...
    def DrawQuad(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawQuadFilled(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], color: int = 0xFFFFFFFF) -> None: ...
    def DrawPoly(self, center: Tuple[float, float], radius: float, color: int = 0xFFFFFFFF, segments: int = 3, thickness: float = 1.0) -> None: ...
    def DrawPolyFilled(self, center: Tuple[float, float], radius: float, color: int = 0xFFFFFFFF, segments: int = 3) -> None: ...
    def DrawCubeOutline(self, center: Tuple[float, float, float], size: Tuple[float, float, float], color: int = 0xFFFFFFFF, use_occlusion: bool = True) -> None: ...
    def DrawCubeFilled(self, center: Tuple[float, float, float], size: Tuple[float, float, float], color: int = 0xFFFFFFFF, use_occlusion: bool = True) -> None: ...

    # 3D drawing
    def DrawLine3D(self, _from: Tuple[float, float, float], to: Tuple[float, float, float], color: int = 0xFFFFFFFF, use_occlusion: bool = True, segments: int = 16, floor_offset: float = 0.0) -> None: ...
    def DrawTriangle3D(self, p1: Tuple[float, float, float], p2: Tuple[float, float, float], p3: Tuple[float, float, float], color: int = 0xFFFFFFFF, use_occlusion: bool = True, edge_segments: int = 16, floor_offset: float = 0.0) -> None: ...
    def DrawTriangleFilled3D(self, p1: Tuple[float, float, float], p2: Tuple[float, float, float], p3: Tuple[float, float, float], color: int = 0xFFFFFFFF, use_occlusion: bool = True, edge_segments: int = 16, floor_offset: float = 0.0) -> None: ...
    def DrawQuad3D(self, p1: Tuple[float, float, float], p2: Tuple[float, float, float], p3: Tuple[float, float, float], p4: Tuple[float, float, float], color: int = 0xFFFFFFFF, use_occlusion: bool = True, edge_segments: int = 16, floor_offset: float = 0.0) -> None: ...
    def DrawQuadFilled3D(self, p1: Tuple[float, float, float], p2: Tuple[float, float, float], p3: Tuple[float, float, float], p4: Tuple[float, float, float], color: int = 0xFFFFFFFF, use_occlusion: bool = True, segments: int = 16, floor_offset: float = 0.0) -> None: ...
    def DrawPoly3D(self, center: Tuple[float, float, float], radius: float, color: int = 0xFFFFFFFF, numSegments: int = 3, autoZ: bool = True, use_occlusion: bool = True, segments: int = 16, floor_offset: float = 0.0) -> None: ...
    def DrawPolyFilled3D(self, center: Tuple[float, float, float], radius: float, color: int = 0xFFFFFFFF, numSegments: int = 3, autoZ: bool = True, use_occlusion: bool = True, segments: int = 16, floor_offset: float = 0.0) -> None: ...

    def Setup3DView(self) -> None: ...
    def ApplyStencilMask(self) -> None: ...
    def ResetStencilMask(self) -> None: ...

    def DrawTexture(self, file_path: str, screen_pos_x: float, screen_pos_y: float, width: float = 100.0, height: float = 100.0, int_tint: int = 0xFFFFFFFF) -> None: ...
    def DrawTexture3D(self, file_path: str, world_pos_x: float, world_pos_y: float, world_pos_z: float, width: float = 100.0, height: float = 100.0, use_occlusion: bool = True, int_tint: int = 0xFFFFFFFF) -> None: ...
    def DrawQuadTextured3D(self, file_path: str, p1: Tuple[float, float, float], p2: Tuple[float, float, float], p3: Tuple[float, float, float], p4: Tuple[float, float, float], use_occlusion: bool = True, int_tint: int = 0xFFFFFFFF) -> None: ...
    def SaveGeometryToFile(self, filename: str, min_x: float, min_y: float, max_x: float, max_y: float) -> None: ...

    # Shader-based (no-texture) draws, occluded in the world pass.
    def DrawBeam3D(self, x: float, y: float, z: float, height: float = 300.0, radius: float = 60.0,
                   argb: int = 0xFF20FF40, top_alpha: float = 0.0, additive: bool = True) -> None: ...
    # vertices = list of (x, y, z, argb) world-space tuples (up = -z), 3 per triangle.
    def draw_shaded_3d(self, vertices: List[Tuple[float, float, float, int]],
                       additive: bool = True, use_occlusion: bool = True) -> None: ...
    # Like draw_shaded_3d but MAX blend: overlapping quads take the brightest, never sum.
    def draw_shaded_3d_max(self, vertices: List[Tuple[float, float, float, int]],
                           use_occlusion: bool = True) -> None: ...
    def set_occlusion_tuning(self, near_z: float, far_z: float, zfunc: int, reverse_z: bool) -> None: ...
    def get_depth_diagnostics(self) -> str: ...
    def draw_self_occlusion_test(self) -> None: ...

# Shared DXOverlay singleton (same object every call). Prefer over DXOverlay().
def get_overlay() -> DXOverlay: ...
