# PyImGui stub â€” Reforged Native surface (2026-07-06)
# Matches imgui_bindings.cpp + sub-module registrars (types, enums, style, docking, drawlist, io, addons).
# ImGui_Legacy 1.92.x docking branch. Full parity with legacy API surface preserved.

from typing import Optional, Tuple, List, Any, overload
from enum import Enum, IntEnum

# ---- TYPES --------
class Vec2:
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

class Vec4:
    x: float
    y: float
    z: float
    w: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 0.0) -> None: ...

class StyleConfig:
    """Live mutable view of the current ImGuiStyle."""
    Alpha: float
    DisabledAlpha: float
    WindowPadding: Vec2
    WindowRounding: float
    WindowBorderSize: float
    WindowMinSize: Vec2
    WindowTitleAlign: Vec2
    ChildRounding: float
    ChildBorderSize: float
    PopupRounding: float
    PopupBorderSize: float
    FramePadding: Vec2
    FrameRounding: float
    FrameBorderSize: float
    ItemSpacing: Vec2
    ItemInnerSpacing: Vec2
    CellPadding: Vec2
    TouchExtraPadding: Vec2
    IndentSpacing: float
    ColumnsMinSpacing: float
    ScrollbarSize: float
    ScrollbarRounding: float
    GrabMinSize: float
    GrabRounding: float
    TabRounding: float
    TabBorderSize: float
    TabBarBorderSize: float
    TabMinWidthForCloseButton: float
    TableAngledHeadersAngle: float
    ColorButtonPosition: int
    ButtonTextAlign: Vec2
    SelectableTextAlign: Vec2
    SeparatorTextBorderSize: float
    SeparatorTextAlign: Vec2
    SeparatorTextPadding: Vec2
    DisplayWindowPadding: Vec2
    DisplaySafeAreaPadding: Vec2
    MouseCursorScale: float
    AntiAliasedLines: bool
    AntiAliasedLinesUseTex: bool
    AntiAliasedFill: bool
    CurveTessellationTol: float
    CircleTessellationMaxError: float
    @property
    def Colors(self) -> List[Vec4]: ...

def get_style() -> StyleConfig: ...

class SortDirection(IntEnum):
    NoDirection = 0
    Ascending = 1
    Descending = 2

class TableColumnSortSpecs:
    @property
    def ColumnIndex(self) -> int: ...
    @property
    def SortDirection(self) -> SortDirection: ...

class TableSortSpecs:
    @property
    def SpecsCount(self) -> int: ...
    @property
    def SpecsDirty(self) -> bool: ...
    @property
    def Specs(self) -> Optional[TableColumnSortSpecs]: ...

class DrawList:
    """ImDrawList wrapper â€” obtain via get_window_draw_list() / get_foreground_draw_list() / get_background_draw_list()."""
    def add_line(self, p1: Tuple[float, float], p2: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
    def add_rect(self, p_min: Tuple[float, float], p_max: Tuple[float, float], col: int, rounding: float = 0.0, flags: int = 0, thickness: float = 1.0) -> None: ...
    def add_rect_filled(self, p_min: Tuple[float, float], p_max: Tuple[float, float], col: int, rounding: float = 0.0, flags: int = 0) -> None: ...
    def add_circle(self, center: Tuple[float, float], radius: float, col: int, num_segments: int = 0, thickness: float = 1.0) -> None: ...
    def add_circle_filled(self, center: Tuple[float, float], radius: float, col: int, num_segments: int = 0) -> None: ...
    def add_text(self, pos: Tuple[float, float], col: int, text: str) -> None: ...
    def add_triangle(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
    def add_triangle_filled(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int) -> None: ...
    def add_quad(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
    def add_quad_filled(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int) -> None: ...
    def add_polyline(self, points: List[Tuple[float, float]], col: int, flags: int = 0, thickness: float = 1.0) -> None: ...
    def add_convex_poly_filled(self, points: List[Tuple[float, float]], col: int) -> None: ...
    def add_bezier_cubic(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int, thickness: float = 1.0, num_segments: int = 0) -> None: ...
    def add_bezier_quadratic(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int, thickness: float = 1.0, num_segments: int = 0) -> None: ...
    def path_clear(self) -> None: ...
    def path_line_to(self, pos: Tuple[float, float]) -> None: ...
    def path_fill_convex(self, col: int) -> None: ...
    def path_stroke(self, col: int, flags: int = 0, thickness: float = 1.0) -> None: ...
    def path_arc_to(self, center: Tuple[float, float], radius: float, a_min: float, a_max: float, num_segments: int = 0) -> None: ...
    def path_arc_to_fast(self, center: Tuple[float, float], radius: float, a_min: int, a_max: int) -> None: ...
    def path_bezier_cubic_curve_to(self, p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], num_segments: int = 0) -> None: ...
    def path_bezier_quadratic_curve_to(self, p2: Tuple[float, float], p3: Tuple[float, float], num_segments: int = 0) -> None: ...
    def path_rect(self, rect_min: Tuple[float, float], rect_max: Tuple[float, float], rounding: float = 0.0, flags: int = 0) -> None: ...
    def add_image(self, tex_id: int, p_min: Tuple[float, float], p_max: Tuple[float, float], uv_min: Tuple[float, float] = (0,0), uv_max: Tuple[float, float] = (1,1), col: int = 0xFFFFFFFF) -> None: ...
    def add_image_rounded(self, tex_id: int, p_min: Tuple[float, float], p_max: Tuple[float, float], uv_min: Tuple[float, float], uv_max: Tuple[float, float], col: int, rounding: float, flags: int = 0) -> None: ...
    def add_image_quad(self, tex_id: int, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], uv1: Tuple[float, float] = (0,0), uv2: Tuple[float, float] = (1,0), uv3: Tuple[float, float] = (1,1), uv4: Tuple[float, float] = (0,1), col: int = 0xFFFFFFFF) -> None: ...
    def prim_reserve(self, idx_count: int, vtx_count: int) -> None: ...
    def prim_quad_uv(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], d: Tuple[float, float], uv_a: Tuple[float, float], uv_b: Tuple[float, float], uv_c: Tuple[float, float], uv_d: Tuple[float, float], col: int) -> None: ...
    def prim_rect(self, a: Tuple[float, float], b: Tuple[float, float], col: int) -> None: ...
    def prim_rect_uv(self, a: Tuple[float, float], b: Tuple[float, float], uv_a: Tuple[float, float], uv_b: Tuple[float, float], col: int) -> None: ...
    def push_clip_rect(self, clip_rect_min: Tuple[float, float], clip_rect_max: Tuple[float, float], intersect: bool = False) -> None: ...
    def push_clip_rect_full_screen(self) -> None: ...
    def pop_clip_rect(self) -> None: ...
    def push_texture_id(self, texture_id: int) -> None: ...
    def pop_texture_id(self) -> None: ...
    def get_clip_rect_min(self) -> Tuple[float, float]: ...
    def get_clip_rect_max(self) -> Tuple[float, float]: ...

def get_window_draw_list() -> DrawList: ...
def get_foreground_draw_list() -> DrawList: ...
def get_background_draw_list() -> DrawList: ...

# Flat draw_list functions (legacy surface â€” each operates on GetWindowDrawList())
def draw_list_add_line(x1: float, y1: float, x2: float, y2: float, col: int, thickness: float = 1.0) -> None: ...
def draw_list_add_rect(x1: float, y1: float, x2: float, y2: float, col: int, rounding: float = 0.0, rounding_corners_flags: int = 0, thickness: float = 1.0) -> None: ...
def draw_list_add_rect_filled(x1: float, y1: float, x2: float, y2: float, col: int, rounding: float = 0.0, rounding_corners_flags: int = 0) -> None: ...
def draw_list_add_circle(x: float, y: float, radius: float, col: int, num_segments: int = 0, thickness: float = 1.0) -> None: ...
def draw_list_add_circle_filled(x: float, y: float, radius: float, col: int, num_segments: int = 0) -> None: ...
def draw_list_add_text(x: float, y: float, col: int, text: str) -> None: ...
def draw_list_add_triangle(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, col: int, thickness: float = 1.0) -> None: ...
def draw_list_add_triangle_filled(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, col: int) -> None: ...
def draw_list_add_quad(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, x4: float, y4: float, col: int, thickness: float = 1.0) -> None: ...
def draw_list_add_quad_filled(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float, x4: float, y4: float, col: int) -> None: ...

# IO access
class ImGuiIO:
    display_size: Vec2
    display_size_x: float
    display_size_y: float
    delta_time: float
    framerate: float
    mouse_pos: Vec2
    mouse_pos_x: float
    mouse_pos_y: float
    mouse_pos_prev_x: float
    mouse_pos_prev_y: float
    mouse_wheel: float
    mouse_wheel_h: float
    key_ctrl: bool
    key_shift: bool
    key_alt: bool
    key_super: bool
    want_capture_mouse: bool
    want_capture_keyboard: bool
    want_text_input: bool
    want_set_mouse_pos: bool
    want_save_ini_settings: bool
    backend_flags: int
    metrics_render_vertices: int
    metrics_render_indices: int
    metrics_active_windows: int
    config_flags: int
    mouse_draw_cursor: bool
    ini_saving_rate: float
    mouse_double_click_time: float
    mouse_drag_threshold: float
    config_docking_no_split: bool
    config_docking_with_shift: bool
    config_windows_move_from_title_bar_only: bool
    config_input_text_cursor_blink: bool
    def mouse_down(self, button: int) -> bool: ...
    def add_config_flag(self, flag: int) -> None: ...
    def remove_config_flag(self, flag: int) -> None: ...
    def has_config_flag(self, flag: int) -> bool: ...
    def has_backend_flag(self, flag: int) -> bool: ...

def get_io() -> ImGuiIO: ...

class ConfigFlags(IntEnum):
    NoFlag = 0
    NavEnableKeyboard = 1
    NavEnableGamepad = 2
    NoMouse = 16
    NoMouseCursorChange = 32
    NoKeyboard = 64
    DockingEnable = 128
    ViewportsEnable = 1024
    DpiEnableScaleFonts = 16384
    DpiEnableScaleViewports = 32768
    NavNoCaptureKeyboard = 8

class BackendFlags(IntEnum):
    NoFlag = 0
    HasGamepad = 1
    HasMouseCursors = 2
    HasSetMousePos = 4
    RendererHasVtxOffset = 8
    RendererHasTextures = 16
    RendererHasViewports = 1024
    PlatformHasViewports = 2048
    HasMouseHoveredViewport = 4096

# ---- WINDOW --------
class WindowFlags(IntEnum):
    NoFlag = 0
    NoTitleBar = 1
    NoResize = 2
    NoMove = 4
    NoScrollbar = 8
    NoScrollWithMouse = 16
    NoCollapse = 32
    AlwaysAutoResize = 64
    NoBackground = 128
    NoSavedSettings = 256
    NoMouseInputs = 512
    MenuBar = 1024
    HorizontalScrollbar = 2048
    NoFocusOnAppearing = 4096
    NoBringToFrontOnFocus = 8192
    AlwaysVerticalScrollbar = 16384
    AlwaysHorizontalScrollbar = 32768
    NoNavInputs = 65536
    NoNavFocus = 131072
    UnsavedDocument = 262144
    NoNav = 196608
    NoDecoration = 43
    NoInputs = 66048
    NavFlattened = 524288
    Docking = 1073741824  # fabricated opt-in docking flag (1<<30); windows are non-dockable unless this is set
    ChildWindow = 1048576
    Tooltip = 2097152
    Popup = 4194304
    Modal = 8388608
    ChildMenu = 16777216

class SelectableFlags(IntEnum):
    NoFlag = 0
    DontClosePopups = 1
    SpanAllColumns = 2
    AllowDoubleClick = 4
    Disabled = 8
    AllowItemOverlap = 16

class TableFlags(IntEnum):
    NoFlag = 0
    Resizable = 1
    Reorderable = 2
    Hideable = 4
    Sortable = 8
    NoSavedSettings = 16
    ContextMenuInBody = 32
    RowBg = 64
    BordersInnerH = 128
    BordersOuterH = 256
    BordersInnerV = 512
    BordersOuterV = 1024
    Borders = 1920
    NoBordersInBody = 2048
    SizingFixedFit = 4096
    SizingFixedSame = 8192
    SizingStretchProp = 16384
    SizingStretchSame = 32768
    NoHostExtendX = 65536
    NoHostExtendY = 131072
    NoKeepColumnsVisible = 262144
    PreciseWidths = 524288
    NoClip = 1048576
    PadOuterX = 2097152
    NoPadOuterX = 4194304
    NoPadInnerX = 8388608
    ScrollX = 16777216
    ScrollY = 33554432
    SortMulti = 67108864
    SortTristate = 134217728

class TableColumnFlags(IntEnum):
    NoFlag = 0
    DefaultHide = 1
    DefaultSort = 2
    WidthStretch = 4
    WidthFixed = 8
    NoResize = 16
    NoReorder = 32
    NoHide = 64
    NoClip = 128
    NoSort = 256
    NoSortAscending = 512
    NoSortDescending = 1024
    IndentEnable = 2048
    IndentDisable = 4096

class InputTextFlags(IntEnum):
    NoFlag = 0
    CharsDecimal = 1
    CharsHexadecimal = 2
    CharsUppercase = 4
    CharsNoBlank = 8
    AutoSelectAll = 16
    EnterReturnsTrue = 32
    CallbackCompletion = 64
    CallbackHistory = 128
    CallbackAlways = 256
    CallbackCharFilter = 512
    AllowTabInput = 1024
    CtrlEnterForNewLine = 2048
    NoHorizontalScroll = 4096
    ReadOnly = 8192
    Password = 16384
    NoUndoRedo = 32768
    CharsScientific = 65536

class ImGuiComboFlags(IntEnum):
    NoFlag = 0
    PopupAlignLeft = 1
    HeightSmall = 2
    HeightRegular = 4
    HeightLarge = 8
    HeightLargest = 16
    NoArrowButton = 32
    NoPreview = 64

class ImGuiCond(IntEnum):
    None_ = 0
    Always = 1
    Once = 2
    FirstUseEver = 4
    Appearing = 8

class ChildFlags(IntEnum):
    NoFlag = 0; Borders = 1; AlwaysUseWindowPadding = 2; ResizeX = 4
    ResizeY = 8; AutoResizeX = 16; AutoResizeY = 32; AlwaysAutoResize = 64
    FrameStyle = 128

class TreeNodeFlags(IntEnum):
    NoFlag = 0; Selected = 1; Framed = 2; NoTreePushOnOpen = 4
    NoAutoOpenOnLog = 8; DefaultOpen = 16; OpenOnDoubleClick = 32
    OpenOnArrow = 64; Leaf = 128; Bullet = 256; FramePadding = 512
    SpanAvailWidth = 1024; SpanFullWidth = 2048; NavLeftJumpsBackHere = 4096
    CollapsingHeader = 8192

class PopupFlags(IntEnum):
    NoFlag = 0; MouseButtonLeft = 1; MouseButtonRight = 2
    MouseButtonMiddle = 4; NoOpenOverExistingPopup = 8; NoOpenOverItems = 16
    AnyPopupId = 32; AnyPopupLevel = 64

class TabBarFlags(IntEnum):
    NoFlag = 0; Reorderable = 1; AutoSelectNewTabs = 2
    TabListPopupButton = 4; NoCloseWithMiddleMouseButton = 8
    NoTabListScrollingButtons = 16; NoTooltip = 32
    DrawSelectedOverline = 64; FittingPolicyResizeDown = 128
    FittingPolicyScroll = 256

class TabItemFlags(IntEnum):
    NoFlag = 0; UnsavedDocument = 1; SetSelected = 2
    NoCloseWithMiddleMouseButton = 4; NoPushId = 8; NoTooltip = 16
    NoReorder = 32; Leading = 64; Trailing = 128
    NoAssumedClosure = 256

class FocusedFlags(IntEnum):
    NoFlag = 0; ChildWindows = 1; RootWindow = 2; AnyWindow = 4
    RootAndChildWindows = 6

class HoveredFlags(IntEnum):
    NoFlag = 0; ChildWindows = 1; RootWindow = 2; AnyWindow = 4
    AllowWhenBlockedByPopup = 8; AllowWhenBlockedByActiveItem = 32
    AllowWhenOverlapped = 64; AllowWhenDisabled = 128; ForTooltip = 1024
    ForNavigation = 2048

class DockNodeFlags(IntEnum):
    NoFlag = 0; KeepAliveOnly = 1; NoDockingOverCentralNode = 4
    PassthruCentralNode = 8; NoDockingSplit = 16; NoResize = 32
    AutoHideTabBar = 64; NoUndocking = 128

class DragDropFlags(IntEnum):
    NoFlag = 0; SourceNoPreviewTooltip = 1; SourceNoDisableHover = 2
    SourceNoHoldToOpenOthers = 4; SourceAllowNullID = 8; SourceExtern = 16
    PayloadAutoExpire = 32; PayloadNoCrossContext = 64
    PayloadNoCrossProcess = 128; AcceptBeforeDelivery = 1024
    AcceptNoDrawDefaultRect = 2048; AcceptNoPreviewTooltip = 4096
    AcceptPeekOnly = 8192

class SliderFlags(IntEnum):
    NoFlag = 0; AlwaysClamp = 16; Logarithmic = 32; NoRoundToFormat = 64
    NoInput = 128

class ButtonFlags(IntEnum):
    NoFlag = 0; MouseButtonLeft = 1; MouseButtonRight = 2
    MouseButtonMiddle = 4; EnableNav = 8

class TableRowFlags(IntEnum):
    NoFlag = 0; Headers = 1

class DrawFlags(IntEnum):
    NoFlag = 0; Closed = 1
    RoundCornersTopLeft = 4; RoundCornersTopRight = 8
    RoundCornersBottomLeft = 16; RoundCornersBottomRight = 32
    RoundCornersNone = 64; RoundCornersTop = 12; RoundCornersBottom = 48
    RoundCornersLeft = 20; RoundCornersRight = 40; RoundCornersAll = 60

class ColorEditFlags(IntEnum):
    NoFlag = 0; NoAlpha = 2; NoPicker = 4; NoOptions = 8
    NoSmallPreview = 16; NoInputs = 32; NoTooltip = 64; NoLabel = 128
    NoSidePreview = 256; NoDragDrop = 512; NoBorder = 1024
    AlphaBar = 2048; AlphaPreview = 4096; AlphaPreviewHalf = 8192
    HDR = 16384; DisplayRGB = 32768; DisplayHSV = 65536
    DisplayHex = 131072; Uint8 = 262144; Float = 524288
    PickerHueBar = 1048576; PickerHueWheel = 2097152
    InputRGB = 4194304; InputHSV = 8388608

class MouseButton(IntEnum):
    Left = 0; Right = 1; Middle = 2; Count = 3

class MouseCursor(IntEnum):
    None_ = -1; Arrow = 0; TextInput = 1; ResizeAll = 2
    ResizeNS = 3; ResizeEW = 4; ResizeNESW = 5; ResizeNWSE = 6
    Hand = 7; NotAllowed = 8

class ImGuiCol(IntEnum):
    Text = 0; TextDisabled = 1; WindowBg = 2; ChildBg = 3; PopupBg = 4
    Border = 5; BorderShadow = 6; FrameBg = 7; FrameBgHovered = 8
    FrameBgActive = 9; TitleBg = 10; TitleBgActive = 11
    TitleBgCollapsed = 12; MenuBarBg = 13; ScrollbarBg = 14
    ScrollbarGrab = 15; ScrollbarGrabHovered = 16
    ScrollbarGrabActive = 17; CheckMark = 18; SliderGrab = 19
    SliderGrabActive = 20; Button = 21; ButtonHovered = 22
    ButtonActive = 23; Header = 24; HeaderHovered = 25
    HeaderActive = 26; Separator = 27; SeparatorHovered = 28
    SeparatorActive = 29; ResizeGrip = 30; ResizeGripHovered = 31
    ResizeGripActive = 32; Tab = 33; TabHovered = 34; TabActive = 35
    TabUnfocused = 36; TabUnfocusedActive = 37; PlotLines = 38
    PlotLinesHovered = 39; PlotHistogram = 40; PlotHistogramHovered = 41
    TableHeaderBg = 42; TableBorderStrong = 43; TableBorderLight = 44
    TableRowBg = 45; TableRowBgAlt = 46; TextLink = 47
    TextSelectedBg = 48; DragDropTarget = 49; NavHighlight = 50
    NavWindowingHighlight = 51; NavWindowingDimBg = 52
    ModalWindowDimBg = 53

class ImGuiStyleVar(IntEnum):
    Alpha = 0; DisabledAlpha = 1; WindowPadding = 2; WindowRounding = 3
    WindowBorderSize = 4; WindowMinSize = 5; WindowTitleAlign = 6
    ChildRounding = 7; ChildBorderSize = 8; PopupRounding = 9
    PopupBorderSize = 10; FramePadding = 11; FrameRounding = 12
    FrameBorderSize = 13; ItemSpacing = 14; ItemInnerSpacing = 15
    IndentSpacing = 16; CellPadding = 17; ScrollbarSize = 18
    ScrollbarRounding = 19; GrabMinSize = 20; GrabRounding = 21
    ImageRounding = 22; ImageBorderSize = 23; TabRounding = 24
    TabBorderSize = 25; TabBarBorderSize = 26; TabBarOverlineSize = 27
    TableAngledHeadersAngle = 28; TableAngledHeadersTextAlign = 29
    ButtonTextAlign = 30; SelectableTextAlign = 31
    SeparatorTextBorderSize = 32; SeparatorTextAlign = 33
    SeparatorTextPadding = 34

@overload
def begin(name: str, dockable: bool = False) -> bool: ...
@overload
def begin(name: str, flags: int, dockable: bool = False) -> bool: ...
@overload
def begin(name: str, p_open: Optional[bool], flags: int = 0, dockable: bool = False) -> Tuple[bool, bool]:
    """Returns (visible, still_open). still_open is True unless user clicked X."""
    ...
def begin_with_close(name: str, p_open: bool, flags: int = 0) -> Tuple[bool, bool]:
    """Window with a close [X] button. Returns (visible, still_open)."""
    ...
def end() -> None: ...
def begin_child(id: str, size: Tuple[float, float] = (0,0), border: int = 0, flags: int = 0) -> bool: ...
def end_child() -> None: ...
def begin_group() -> None: ...
def end_group() -> None: ...
def begin_disabled(disabled: bool = True) -> None: ...
def end_disabled() -> None: ...

# Window setup
@overload
def set_next_window_pos(x: float, y: float, cond: int = 0) -> None: ...
@overload
def set_next_window_pos(pos: Tuple[float, float], cond: int = 0, pivot: Tuple[float, float] = (0,0)) -> None: ...
@overload
def set_next_window_size(width: float, height: float, cond: int = 0) -> None: ...
@overload
def set_next_window_size(size: Tuple[float, float], cond: int = 0) -> None: ...
def set_next_window_size_constraints(size_min: Tuple[float, float], size_max: Tuple[float, float]) -> None: ...
def set_next_window_content_size(size: Tuple[float, float]) -> None: ...
def set_next_window_collapsed(collapsed: bool, cond: int = 0) -> None: ...
def set_next_window_focus() -> None: ...
def set_next_window_bg_alpha(alpha: float) -> None: ...
def set_next_window_scroll(scroll: Tuple[float, float]) -> None: ...
def set_next_window_viewport(viewport_id: int) -> None: ...
def set_next_window_detached(
    detached: bool = True,
    no_taskbar_icon: bool = False,
    no_decoration: bool = False,
    top_level: bool = True,
) -> None: ...
def set_next_window_main_viewport() -> None: ...
@overload
def set_window_pos(x: float, y: float, cond: int = 0) -> None: ...
@overload
def set_window_pos(pos: Tuple[float, float], cond: int = 0) -> None: ...
@overload
def set_window_size(width: float, height: float, cond: int = 0) -> None: ...
@overload
def set_window_size(size: Tuple[float, float], cond: int = 0) -> None: ...
def set_window_collapsed(collapsed: bool, cond: int = 0) -> None: ...
def set_window_focus(name: str) -> None: ...

# Window query
def get_window_pos() -> Tuple[float, float]: ...
def get_window_size() -> Tuple[float, float]: ...
def get_window_width() -> float: ...
def get_window_height() -> float: ...
def get_content_region_avail() -> Tuple[float, float]: ...
def get_window_content_region_min() -> Tuple[float, float]: ...
def get_window_content_region_max() -> Tuple[float, float]: ...
def is_window_appearing() -> bool: ...
def is_window_collapsed() -> bool: ...
def is_window_focused(flags: int = 0) -> bool: ...
def is_window_hovered(flags: int = 0) -> bool: ...
def is_rect_visible(size: Tuple[float, float]) -> bool: ...

# ---- LAYOUT --------
def separator() -> None: ...
def separator_text(label: str) -> None: ...
def same_line(offset_from_start_x: float = 0.0, spacing: float = -1.0) -> None: ...
def spacing() -> None: ...
def new_line() -> None: ...
def dummy(size: Tuple[float, float]) -> None: ...
def indent(indent_w: float = 0.0) -> None: ...
def unindent(indent_w: float = 0.0) -> None: ...
def align_text_to_frame_padding() -> None: ...
def get_frame_height() -> float: ...
def get_frame_height_with_spacing() -> float: ...
def get_font_size() -> float: ...

# Font switching
def push_font(font_index: int = 0) -> None: ...
def pop_font() -> None: ...
def push_font_scaled(font_index: int, scale: float = 1.0) -> None: ...
def pop_font_scaled() -> None: ...

# ---- TEXT --------
def text_unformatted(text: str, text_end: Optional[str] = None) -> None: ...
def text_link(label: str) -> bool: ...
def text_link_open_url(label: str, url: str = None) -> bool: ...
def text(text: str) -> None: ...
@overload
def text_colored(color: Tuple[float, float, float, float], text: str) -> None: ...
@overload
def text_colored(r: float, g: float, b: float, a: float, text: str) -> None: ...
@overload
def text_colored(text: str, color: Tuple[float, float, float, float]) -> None: ...
def text_disabled(text: str) -> None: ...
def text_wrapped(text: str) -> None: ...
def bullet_text(text: str) -> None: ...
def label_text(label: str, text: str) -> None: ...

# ---- WIDGETS ----â•
@overload
def button(label: str, size: Tuple[float, float] = (0,0)) -> bool: ...
@overload
def button(label: str, width: float = 0.0, height: float = 0.0) -> bool: ...
def small_button(label: str) -> bool: ...
def invisible_button(str_id: str, size: Tuple[float, float], flags: int = 0) -> bool: ...
def arrow_button(str_id: str, dir: int) -> bool: ...
def checkbox(label: str, value: bool) -> bool: ...
def radio_button(label: str, value: int, v_button: int) -> int: ...
def progress_bar(fraction: float, size_arg_x: float = -1.0, size_arg_y: float = 0.0, overlay: Optional[str] = None) -> None: ...
def bullet() -> None: ...
def checkbox_flags(label: str, flags: int, flags_value: int) -> int: ...

# Sliders
def slider_float(label: str, v: float, v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> float: ...
def slider_int(label: str, v: int, v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> int: ...
def slider_angle(label: str, v_rad: float, v_degrees_min: float = -360.0, v_degrees_max: float = 360.0, format: str = "%.0f deg", flags: int = 0) -> float: ...
def v_slider_float(label: str, size: Tuple[float, float], v: float, v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> float: ...
def v_slider_int(label: str, size: Tuple[float, float], v: int, v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> int: ...
def slider_float2(label: str, v: Tuple[float, float], v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> Tuple[float, float]: ...
def slider_float3(label: str, v: Tuple[float, float, float], v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float]: ...
def slider_float4(label: str, v: Tuple[float, float, float, float], v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float, float]: ...
def slider_int2(label: str, v: Tuple[int, int], v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> Tuple[int, int]: ...
def slider_int3(label: str, v: Tuple[int, int, int], v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> Tuple[int, int, int]: ...
def slider_int4(label: str, v: Tuple[int, int, int, int], v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> Tuple[int, int, int, int]: ...

# Drags
def drag_float(label: str, v: float, v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> float: ...
def drag_float_range2(label: str, v_current_min: float, v_current_max: float, v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", format_max: str = None, flags: int = 0) -> Tuple[float, float]: ...
def drag_int(label: str, v: int, v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> int: ...
def drag_int_range2(label: str, v_current_min: int, v_current_max: int, v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", format_max: str = None, flags: int = 0) -> Tuple[int, int]: ...
def drag_float2(label: str, v: Tuple[float, float], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> Tuple[float, float]: ...
def drag_float3(label: str, v: Tuple[float, float, float], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float]: ...
def drag_float4(label: str, v: Tuple[float, float, float, float], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float, float]: ...
def drag_int2(label: str, v: Tuple[int, int], v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> Tuple[int, int]: ...
def drag_int3(label: str, v: Tuple[int, int, int], v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> Tuple[int, int, int]: ...
def drag_int4(label: str, v: Tuple[int, int, int, int], v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> Tuple[int, int, int, int]: ...

# ---- INPUT --------
def input_float(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = "%.3f", flags: int = 0) -> float: ...
def input_float2(label: str, v: Tuple[float, float], format: str = "%.3f", flags: int = 0) -> Tuple[float, float]: ...
def input_float3(label: str, v: Tuple[float, float, float], format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float]: ...
def input_float4(label: str, v: Tuple[float, float, float, float], format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float, float]: ...
def input_int(label: str, v: int, step: int = 1, step_fast: int = 100, flags: int = 0) -> int: ...
def input_int2(label: str, v: Tuple[int, int], flags: int = 0) -> Tuple[int, int]: ...
def input_int3(label: str, v: Tuple[int, int, int], flags: int = 0) -> Tuple[int, int, int]: ...
def input_int4(label: str, v: Tuple[int, int, int, int], flags: int = 0) -> Tuple[int, int, int, int]: ...
def input_double(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = "%.6f", flags: int = 0) -> float: ...
def input_text(label: str, text: str = "", flags: int = 0) -> str: ...
def input_text_with_hint(label: str, hint: str, text: str = "", flags: int = 0) -> str: ...
def input_text_multiline(label: str, text: str = "", size: Tuple[float, float] = (0,0), flags: int = 0) -> str: ...

# Combo / List box
def begin_combo(label: str, preview_value: str, flags: int = 0) -> bool: ...
def end_combo() -> None: ...
def combo(label: str, current_item: int, items: List[str]) -> int: ...
def begin_list_box(label: str, size: Tuple[float, float] = (0,0)) -> bool: ...
def end_list_box() -> None: ...
def list_box(label: str, current_item: int, items: List[str], height_in_items: int = -1) -> int: ...

# Multi-Select
def begin_multi_select(flags: int = 0, selection_size: int = -1, items_count: int = -1) -> bool: ...
def end_multi_select() -> None: ...

# Selectable
def selectable(label: str, selected: bool = False, flags: int = 0, size: Tuple[float, float] = (0,0)) -> bool: ...

# ---- COLOR --------
def color_edit3(label: str, col: Tuple[float, float, float], flags: int = 0) -> Tuple[float, float, float]: ...
def color_edit4(label: str, col: Tuple[float, float, float, float], flags: int = 0) -> Tuple[float, float, float, float]: ...
def color_picker3(label: str, col: Tuple[float, float, float], flags: int = 0) -> Tuple[float, float, float]: ...
def color_picker4(label: str, col: Tuple[float, float, float, float], flags: int = 0) -> Tuple[float, float, float, float]: ...
def color_button(desc_id: str, col: Tuple[float, float, float, float], flags: int = 0, size: Tuple[float, float] = (0,0)) -> bool: ...
def set_color_edit_options(flags: int) -> None: ...
def color_convert_u32_to_float4(in_: int) -> Tuple[float, float, float, float]: ...
def color_convert_float4_to_u32(in_: Tuple[float, float, float, float]) -> int: ...
def color_convert_rgb_to_hsv(r: float, g: float, b: float) -> Tuple[float, float, float]: ...
def color_convert_hsv_to_rgb(h: float, s: float, v: float) -> Tuple[float, float, float]: ...
def get_color_u32(idx: int, alpha_mul: float = 1.0) -> int: ...
def get_color_u32_vec4(col: Tuple[float, float, float, float]) -> int: ...
def get_style_color_vec4(idx: int) -> Tuple[float, float, float, float]: ...

# ---- IMAGE --------
def image(tex_id: int, size: Tuple[float, float], uv0: Tuple[float, float] = (0,0), uv1: Tuple[float, float] = (1,1)) -> None: ...
def image_with_bg(tex_id: int, size: Tuple[float, float], uv0: Tuple[float, float] = (0,0), uv1: Tuple[float, float] = (1,1), bg_col: Tuple[float, float, float, float] = (0,0,0,0), tint_col: Tuple[float, float, float, float] = (1,1,1,1)) -> None: ...
def image_button(str_id: str, tex_id: int, size: Tuple[float, float], uv0: Tuple[float, float] = (0,0), uv1: Tuple[float, float] = (1,1), bg_col: Tuple[float, float, float, float] = (0,0,0,0), tint_col: Tuple[float, float, float, float] = (1,1,1,1)) -> bool: ...

# ---- TREE / COLLAPSING ----
def tree_node(label: str) -> bool: ...
def tree_node_ex(label: str, flags: int = 0) -> bool: ...
def tree_pop() -> None: ...
def tree_push(str_id: str) -> None: ...
def tree_push_ptr(ptr_id: int) -> None: ...
def get_tree_node_to_label_spacing() -> float: ...
def set_next_item_open(is_open: bool, cond: int = 0) -> None: ...
def set_next_item_storage_id(storage_id: int) -> None: ...
def tree_node_get_open(storage_id: int) -> bool: ...
def collapsing_header(label: str, flags: int = 0) -> bool: ...

# ---- TABS --------
def begin_tab_bar(str_id: str, flags: int = 0) -> bool: ...
def end_tab_bar() -> None: ...
def begin_tab_item(label: str, p_open: bool | None = None, flags: int = 0) -> bool: ...
def begin_tab_item_closable(label: str, p_open: bool= True, flags: int = 0) -> Tuple[bool, bool]: ...
def end_tab_item() -> None: ...
def tab_item_button(label: str, flags: int = 0) -> bool: ...
def set_tab_item_closed(tab_or_docked_window_label: str) -> None: ...

# ---- TABLES --------
@overload
def begin_table(str_id: str, column: int, flags: int = 0, outer_size: Tuple[float, float] = (0,0), inner_width: float = 0.0) -> bool: ...
@overload
def begin_table(str_id: str, column: int, flags: int = 0, width: float = 0.0, height: float = 0.0) -> bool: ...
def end_table() -> None: ...
def table_next_row(row_flags: int = 0, min_row_height: float = 0.0) -> None: ...
def table_next_column() -> bool: ...
def table_set_column_index(column_n: int) -> bool: ...
def table_setup_column(label: str, flags: int = 0, init_width_or_weight: float = 0.0, user_id: int = 0) -> None: ...
def table_setup_scroll_freeze(cols: int, rows: int) -> None: ...
def table_headers_row() -> None: ...
def table_header(label: str) -> None: ...
def table_angled_headers_row() -> None: ...
def table_get_column_count() -> int: ...
def table_get_column_index() -> int: ...
def table_get_row_index() -> int: ...
def table_get_column_name(column_n: int = -1) -> str: ...
def table_get_column_flags(column_n: int = -1) -> int: ...
def table_get_hovered_column() -> int: ...
def table_set_column_enabled(column_n: int, v: bool) -> None: ...
def table_set_bg_color(target: int, color: int, column_n: int = -1) -> None: ...
def table_get_sort_specs() -> Optional[TableSortSpecs]: ...
def clear_sort_specs_dirty() -> None: ...

# Legacy columns
def columns(count: int = 1, id: str = None, borders: bool = True) -> None: ...
def next_column() -> None: ...
def end_columns() -> None: ...
def set_column_width(column_index: int, width: float) -> None: ...
def set_column_offset(column_index: int, offset_x: float) -> None: ...
def get_column_index() -> int: ...
def get_column_width(column_index: int = -1) -> float: ...
def get_column_offset(column_index: int = -1) -> float: ...
def get_columns_count() -> int: ...

# ---- MENUS --------
def begin_menu_bar() -> bool: ...
def end_menu_bar() -> None: ...
def begin_main_menu_bar() -> bool: ...
def end_main_menu_bar() -> None: ...
def begin_menu(label: str, enabled: bool = True) -> bool: ...
def end_menu() -> None: ...
def menu_item(label: str, shortcut: str = None, selected: bool = False, enabled: bool = True) -> bool: ...

#  POPUPS / TOOLTIPS ----
def open_popup(str_id: str, popup_flags: int = 0) -> None: ...
def open_popup_on_item_click(str_id: str = None, popup_flags: int = 0) -> None: ...
def begin_popup(str_id: str, flags: int = 0) -> bool: ...
def end_popup() -> None: ...
def end_popup_modal() -> None: ...
def begin_popup_modal(name: str, p_open: bool = None, flags: int = 0) -> bool: ...
def close_current_popup() -> None: ...
def begin_popup_context_item(str_id: str = None, popup_flags: int = 0) -> bool: ...
def begin_popup_context_window(str_id: str = None, popup_flags: int = 0) -> bool: ...
def begin_popup_context_void(str_id: str = None, popup_flags: int = 0) -> bool: ...
def is_popup_open(str_id: str, flags: int = 0) -> bool: ...
def begin_tooltip() -> None: ...
def end_tooltip() -> None: ...
def set_tooltip(fmt: str) -> None: ...
def show_tooltip(text: str) -> None: ...
def begin_item_tooltip() -> None: ...
def set_item_tooltip(fmt: str) -> None: ...

# ---- CURSOR --------
def get_cursor_pos() -> Tuple[float, float]: ...
def set_cursor_pos(local_pos: Tuple[float, float]) -> None: ...
def get_cursor_pos_x() -> float: ...
def set_cursor_pos_x(local_x: float) -> None: ...
def get_cursor_pos_y() -> float: ...
def set_cursor_pos_y(local_y: float) -> None: ...
def get_cursor_screen_pos() -> Tuple[float, float]: ...
def set_cursor_screen_pos(pos: Tuple[float, float]) -> None: ...
def get_cursor_start_pos() -> Tuple[float, float]: ...

# ---- SCROLLING ----
def get_scroll_x() -> float: ...
def get_scroll_y() -> float: ...
def get_scroll_max_x() -> float: ...
def get_scroll_max_y() -> float: ...
def set_scroll_x(scroll_x: float) -> None: ...
def set_scroll_y(scroll_y: float) -> None: ...
def set_scroll_here_x(center_x_ratio: float = 0.5) -> None: ...
def set_scroll_here_y(center_y_ratio: float = 0.5) -> None: ...
def set_scroll_from_pos_x(local_x: float, center_x_ratio: float = 0.5) -> None: ...
def set_scroll_from_pos_y(local_y: float, center_y_ratio: float = 0.5) -> None: ...

# ---- ITEM QUERY ----
def is_item_hovered(flags: int = 0) -> bool: ...
def is_item_active() -> bool: ...
def is_item_focused() -> bool: ...
def is_item_clicked(mouse_button: int = 0) -> bool: ...
def is_item_visible() -> bool: ...
def is_item_edited() -> bool: ...
def is_item_activated() -> bool: ...
def is_item_deactivated() -> bool: ...
def is_item_deactivated_after_edit() -> bool: ...
def is_item_toggled_open() -> bool: ...
def is_any_item_hovered() -> bool: ...
def is_any_item_active() -> bool: ...
def is_any_item_focused() -> bool: ...
def get_item_id() -> int: ...
def get_item_rect_min() -> Tuple[float, float]: ...
def get_item_rect_max() -> Tuple[float, float]: ...
def get_item_rect_size() -> Tuple[float, float]: ...
def get_item_flags() -> int: ...
def set_item_default_focus() -> None: ...
def set_nav_cursor_visible(visible: bool) -> None: ...
def set_next_item_width(item_width: float) -> None: ...
def set_next_item_allow_overlap() -> None: ...

# ---- ID / FOCUS ----
def push_id(str_id: str) -> None: ...
def push_id_int(int_id: int) -> None: ...
def pop_id() -> None: ...
def get_id(str_id: str) -> int: ...
def get_id_int(int_id: int) -> int: ...
def set_keyboard_focus_here(offset: int = 0) -> None: ...

# ---- KEYBOARD ----
def is_key_down(key: int) -> bool: ...
def is_key_pressed(key: int, repeat: bool = True) -> bool: ...
def is_key_released(key: int) -> bool: ...
def is_key_chord_pressed(key_chord: int) -> bool: ...
def get_key_name(key: int) -> str: ...
def get_key_pressed_amount(key: int, repeat_delay: float, rate: float) -> int: ...
def set_next_frame_want_capture_keyboard(want_capture_keyboard: bool) -> None: ...
def shortcut(key_chord: int, flags: int = 0) -> bool: ...
def set_next_item_shortcut(key_chord: int, flags: int = 0) -> None: ...
def set_item_key_owner(key: int) -> None: ...

# ---- MOUSE --------
def set_mouse_cursor(cursor_type: int) -> None: ...
def get_mouse_cursor() -> int: ...
def get_mouse_pos() -> Tuple[float, float]: ...
def get_mouse_pos_on_opening_current_popup() -> Tuple[float, float]: ...
def is_mouse_down(button: int) -> bool: ...
def is_mouse_clicked(button: int, repeat: bool = False) -> bool: ...
def is_mouse_released(button: int) -> bool: ...
def is_mouse_double_clicked(button: int) -> bool: ...
def is_mouse_released_with_delay(button: int, delay: float) -> bool: ...
def is_mouse_dragging(button: int, lock_threshold: float = -1.0) -> bool: ...
def is_mouse_hovering_rect(r_min: Tuple[float, float], r_max: Tuple[float, float], clip: bool = True) -> bool: ...
def is_any_mouse_down() -> bool: ...
def is_mouse_pos_valid(mouse_pos: Tuple[float, float] = (-3.4028235e38, -3.4028235e38)) -> bool: ...
def get_mouse_clicked_count(button: int) -> int: ...
def get_mouse_drag_delta(button: int = 0, lock_threshold: float = -1.0) -> Tuple[float, float]: ...
def reset_mouse_drag_delta(button: int = 0) -> None: ...
def set_next_frame_want_capture_mouse(want_capture_mouse: bool) -> None: ...

# ---- STYLE --------
def push_style_color(idx: int, col: Tuple[float, float, float, float]) -> None: ...
def push_style_color_u32(idx: int, col_u32: int) -> None: ...
def pop_style_color(count: int = 1) -> None: ...
def push_style_var(idx: int, val: float) -> None: ...
def push_style_var_vec2(idx: int, val: Tuple[float, float]) -> None: ...
def push_style_var_x(idx: int, val_x: float) -> None: ...
def push_style_var_y(idx: int, val_y: float) -> None: ...
def pop_style_var(count: int = 1) -> None: ...
def push_item_flag(option: int, enabled: bool) -> None: ...
def pop_item_flag() -> None: ...
def push_item_width(item_width: float) -> None: ...
def pop_item_width() -> None: ...
def calc_item_width() -> float: ...
def push_text_wrap_pos(wrap_local_pos_x: float = 0.0) -> None: ...
def pop_text_wrap_pos() -> None: ...
def push_button_repeat(repeat: bool) -> None: ...
def pop_button_repeat() -> None: ...
def style_colors_dark(dst=None) -> None: ...
def style_colors_light(dst=None) -> None: ...
def style_colors_classic(dst=None) -> None: ...
def get_style_color_name(idx: int) -> str: ...

# ---- CLIP RECT ----
@overload
def push_clip_rect(clip_rect_min: Tuple[float, float], clip_rect_max: Tuple[float, float], intersect_with_current_clip_rect: bool = False) -> None: ...
@overload
def push_clip_rect(x: float, y: float, width: float, height: float, intersect_with_current_clip_rect: bool = True) -> None: ...
def pop_clip_rect() -> None: ...

# ---- FONT --------
def get_text_line_height() -> float: ...
def get_text_line_height_with_spacing() -> float: ...
def calc_text_size(text: str, text_end: str = None, hide_text_after_double_hash: bool = False, wrap_width: float = -1.0) -> Tuple[float, float]: ...
def get_font() -> Any: ...
def get_font_tex_uv_white_pixel() -> Tuple[float, float]: ...
def set_window_font_scale(s: float) -> None: ...

# ---- CLIPBOARD / LOG ----â•â•
def get_clipboard_text() -> str: ...
def set_clipboard_text(text: str) -> None: ...
def log_to_tty(auto_open_depth: int = -1) -> None: ...
def log_to_file(auto_open_depth: int = -1, filename: str = None) -> None: ...
def log_to_clipboard(auto_open_depth: int = -1) -> None: ...
def log_buttons() -> None: ...
def log_finish() -> None: ...
def get_time() -> float: ...
def get_frame_count() -> int: ...

# ---- INI --------
def load_ini_settings_from_disk(ini_filename: str) -> None: ...
def load_ini_settings_from_memory(ini_data: str, ini_size: int = 0) -> None: ...
def save_ini_settings_to_disk(ini_filename: str) -> None: ...
def save_ini_settings_to_memory() -> str: ...

# ---- DRAG & DROP ----â•â•â•â•
def begin_drag_drop_source(flags: int = 0) -> bool: ...
def set_drag_drop_payload(type: str, data: Any, sz: int, cond: int = 0) -> bool: ...
def end_drag_drop_source() -> None: ...
def begin_drag_drop_target() -> bool: ...
def accept_drag_drop_payload(type: str, flags: int = 0) -> Any: ...
def end_drag_drop_target() -> None: ...
def get_drag_drop_payload() -> Any: ...

#region Viewport
# ---- VIEWPORT ----
def is_docking_enabled() -> bool: ...
def set_docking_enabled(enabled: bool) -> None: ...
def is_multi_viewport_enabled() -> bool: ...
def set_multi_viewport_enabled(enabled: bool) -> None: ...
def has_multi_viewport_support() -> bool: ...
def get_main_viewport() -> Any: ...
def get_window_viewport() -> Any: ...
def get_window_dpi_scale() -> float: ...

#region Plotting
# ---- PLOTTING ----
def plot_lines(label: str, values: List[float], values_offset: int = 0, overlay_text: str = None, scale_min: float = 3.4028235e38, scale_max: float = 3.4028235e38, graph_size: Tuple[float, float] = (0,0)) -> None: ...
def plot_histogram(label: str, values: List[float], values_offset: int = 0, overlay_text: str = None, scale_min: float = 3.4028235e38, scale_max: float = 3.4028235e38, graph_size: Tuple[float, float] = (0,0)) -> None: ...
def value_bool(prefix: str, v: bool) -> None: ...
def value_int(prefix: str, v: int) -> None: ...
def value_uint(prefix: str, v: int) -> None: ...
def value_float(prefix: str, v: float, float_format: str = None) -> None: ...

#region Debug
# ---- DEBUG --------
def show_demo_window() -> None: ...
def show_metrics_window() -> None: ...
def show_debug_log_window() -> None: ...
def show_id_stack_tool_window() -> None: ...
def show_about_window() -> None: ...
def show_style_editor() -> None: ...
def show_style_selector(label: str) -> None: ...
def show_font_selector(label: str) -> None: ...
def show_user_guide() -> None: ...
def get_version() -> str: ...
def debug_flash_style_color(idx: int) -> None: ...
def debug_start_item_picker() -> None: ...
def debug_text_encoding(text: str) -> None: ...

#region Docking
# ---- DOCKING (sub-module) ----â•â•â•â•
def dock_space(id: int, size: Tuple[float, float] = (0,0), flags: int = 0) -> int: ...
def dock_space_over_viewport(dockspace_id: int = 0, flags: int = 0) -> int: ...
def set_next_window_dock_id(dock_id: int, cond: int = 0) -> None: ...
def get_window_dock_id() -> int: ...
def is_window_docked() -> bool: ...
def dock_builder_add_node(node_id: int = 0, flags: int = 0) -> int: ...
def dock_builder_remove_node(node_id: int) -> None: ...
def dock_builder_remove_node_child_nodes(node_id: int) -> None: ...
def dock_builder_remove_node_docked_windows(node_id: int, clear_settings_refs: bool = True) -> None: ...
def dock_builder_set_node_pos(node_id: int, pos: Tuple[float, float]) -> None: ...
def dock_builder_set_node_size(node_id: int, size: Tuple[float, float]) -> None: ...
def dock_builder_split_node(node_id: int, split_dir: int, size_ratio_for_node_at_dir: float) -> Tuple[int, int]: ...
def dock_builder_dock_window(window_name: str, node_id: int) -> None: ...
def dock_builder_finish(node_id: int) -> None: ...

# ---- ADDONS (sub-module) ----â•â•â•â•
# PyImGui.filebrowser â€” FileBrowser class
# PyImGui.hotkey â€” Hotkey class
# PyImGui.markdown â€” Markdown rendering
# PyImGui.memory_editor â€” MemoryEditor class
# PyImGui.anim â€” Animation helpers

#region FileBrowser
# ═══════════════ FILEBROWSER (sub-module) ═══════════════
class _FileBrowserDialogMode(Enum):
    SELECT = 0
    OPEN = 1
    SAVE = 2

class _FileBrowser:
    selected_fn: str
    selected_path: str
    ext: str
    def __init__(self) -> None: ...
    def show_file_dialog(self, label: str, mode: _FileBrowserDialogMode, size: Tuple[float, float] = (0.0, 0.0), valid_types: str = '*.*') -> bool: ...
    def set_current_path(self, path: str) -> None: ...
    def get_current_path(self) -> str: ...
    def set_use_modal(self, modal: bool) -> None: ...

class _FileBrowserModule:
    DialogMode: type[_FileBrowserDialogMode]
    FileBrowser: type[_FileBrowser]

filebrowser: _FileBrowserModule

#region ImPlot
# ═══════════════ IMPLOT (sub-module) ═══════════════
# PyImGui.implot — ImPlot plotting library (full ImPlotSpec-based surface).
# Colors are (r, g, b, a) float tuples; Optional color None = ImPlot auto color.
# Per-item styling is carried by ImPlotSpec (build one with make_spec()).
# Array args are copied by value and empty-guarded (no-op on empty input).

_Col = Tuple[float, float, float, float]

class _ImPlotModule:
    AUTO: int
    # axes (ImAxis)
    X1: int
    X2: int
    X3: int
    Y1: int
    Y2: int
    Y3: int
    # plot flags (ImPlotFlags)
    Flags_None: int
    Flags_NoTitle: int
    Flags_NoLegend: int
    Flags_NoMouseText: int
    Flags_NoInputs: int
    Flags_NoMenus: int
    Flags_NoBoxSelect: int
    Flags_NoFrame: int
    Flags_Equal: int
    Flags_Crosshairs: int
    Flags_CanvasOnly: int
    # axis flags (ImPlotAxisFlags)
    AxisFlags_None: int
    AxisFlags_NoLabel: int
    AxisFlags_NoGridLines: int
    AxisFlags_NoTickMarks: int
    AxisFlags_NoTickLabels: int
    AxisFlags_NoInitialFit: int
    AxisFlags_NoMenus: int
    AxisFlags_NoSideSwitch: int
    AxisFlags_NoHighlight: int
    AxisFlags_Opposite: int
    AxisFlags_Foreground: int
    AxisFlags_Invert: int
    AxisFlags_AutoFit: int
    AxisFlags_RangeFit: int
    AxisFlags_PanStretch: int
    AxisFlags_LockMin: int
    AxisFlags_LockMax: int
    AxisFlags_Lock: int
    AxisFlags_NoDecorations: int
    AxisFlags_AuxDefault: int
    # subplot flags (ImPlotSubplotFlags)
    SubplotFlags_None: int
    SubplotFlags_NoTitle: int
    SubplotFlags_NoLegend: int
    SubplotFlags_NoMenus: int
    SubplotFlags_NoResize: int
    SubplotFlags_NoAlign: int
    SubplotFlags_ShareItems: int
    SubplotFlags_LinkRows: int
    SubplotFlags_LinkCols: int
    SubplotFlags_LinkAllX: int
    SubplotFlags_LinkAllY: int
    SubplotFlags_ColMajor: int
    # legend flags (ImPlotLegendFlags)
    LegendFlags_None: int
    LegendFlags_NoButtons: int
    LegendFlags_NoHighlightItem: int
    LegendFlags_NoHighlightAxis: int
    LegendFlags_NoMenus: int
    LegendFlags_Outside: int
    LegendFlags_Horizontal: int
    LegendFlags_Sort: int
    LegendFlags_Reverse: int
    # mouse-text flags (ImPlotMouseTextFlags)
    MouseTextFlags_None: int
    MouseTextFlags_NoAuxAxes: int
    MouseTextFlags_NoFormat: int
    MouseTextFlags_ShowAlways: int
    # drag-tool flags (ImPlotDragToolFlags)
    DragToolFlags_None: int
    DragToolFlags_NoCursors: int
    DragToolFlags_NoFit: int
    DragToolFlags_NoInputs: int
    DragToolFlags_Delayed: int
    # colormap-scale flags (ImPlotColormapScaleFlags)
    ColormapScaleFlags_None: int
    ColormapScaleFlags_NoLabel: int
    ColormapScaleFlags_Opposite: int
    ColormapScaleFlags_Invert: int
    # item flags (common) + per-plot-type flags — all set on ImPlotSpec.flags
    ItemFlags_None: int
    ItemFlags_NoLegend: int
    ItemFlags_NoFit: int
    LineFlags_None: int
    LineFlags_Segments: int
    LineFlags_Loop: int
    LineFlags_SkipNaN: int
    LineFlags_NoClip: int
    LineFlags_Shaded: int
    ScatterFlags_None: int
    ScatterFlags_NoClip: int
    StairsFlags_None: int
    StairsFlags_PreStep: int
    StairsFlags_Shaded: int
    ShadedFlags_None: int
    BarsFlags_None: int
    BarsFlags_Horizontal: int
    BarGroupsFlags_None: int
    BarGroupsFlags_Horizontal: int
    BarGroupsFlags_Stacked: int
    ErrorBarsFlags_None: int
    ErrorBarsFlags_Horizontal: int
    StemsFlags_None: int
    StemsFlags_Horizontal: int
    InfLinesFlags_None: int
    InfLinesFlags_Horizontal: int
    PieChartFlags_None: int
    PieChartFlags_Normalize: int
    PieChartFlags_IgnoreHidden: int
    PieChartFlags_Exploding: int
    PieChartFlags_NoSliceBorder: int
    HeatmapFlags_None: int
    HeatmapFlags_ColMajor: int
    HistogramFlags_None: int
    HistogramFlags_Horizontal: int
    HistogramFlags_Cumulative: int
    HistogramFlags_Density: int
    HistogramFlags_NoOutliers: int
    HistogramFlags_ColMajor: int
    DigitalFlags_None: int
    ImageFlags_None: int
    TextFlags_None: int
    TextFlags_Vertical: int
    DummyFlags_None: int
    # update condition (ImPlotCond)
    Cond_None: int
    Cond_Always: int
    Cond_Once: int
    # style colors (ImPlotCol)
    Col_FrameBg: int
    Col_PlotBg: int
    Col_PlotBorder: int
    Col_LegendBg: int
    Col_LegendBorder: int
    Col_LegendText: int
    Col_TitleText: int
    Col_InlayText: int
    Col_AxisText: int
    Col_AxisGrid: int
    Col_AxisTick: int
    Col_AxisBg: int
    Col_AxisBgHovered: int
    Col_AxisBgActive: int
    Col_Selection: int
    Col_Crosshairs: int
    Col_COUNT: int
    # style vars (ImPlotStyleVar)
    StyleVar_PlotDefaultSize: int
    StyleVar_PlotMinSize: int
    StyleVar_PlotBorderSize: int
    StyleVar_MinorAlpha: int
    StyleVar_MajorTickLen: int
    StyleVar_MinorTickLen: int
    StyleVar_MajorTickSize: int
    StyleVar_MinorTickSize: int
    StyleVar_MajorGridSize: int
    StyleVar_MinorGridSize: int
    StyleVar_PlotPadding: int
    StyleVar_LabelPadding: int
    StyleVar_LegendPadding: int
    StyleVar_LegendInnerPadding: int
    StyleVar_LegendSpacing: int
    StyleVar_MousePosPadding: int
    StyleVar_AnnotationPadding: int
    StyleVar_FitPadding: int
    StyleVar_DigitalPadding: int
    StyleVar_DigitalSpacing: int
    # axis scale (ImPlotScale)
    Scale_Linear: int
    Scale_Time: int
    Scale_Log10: int
    Scale_SymLog: int
    # markers (ImPlotMarker)
    Marker_None: int
    Marker_Auto: int
    Marker_Circle: int
    Marker_Square: int
    Marker_Diamond: int
    Marker_Up: int
    Marker_Down: int
    Marker_Left: int
    Marker_Right: int
    Marker_Cross: int
    Marker_Plus: int
    Marker_Asterisk: int
    Marker_Vertical: int
    Marker_Horizontal: int
    # built-in colormaps (ImPlotColormap)
    Colormap_Deep: int
    Colormap_Dark: int
    Colormap_Pastel: int
    Colormap_Paired: int
    Colormap_Viridis: int
    Colormap_Plasma: int
    Colormap_Hot: int
    Colormap_Cool: int
    Colormap_Pink: int
    Colormap_Jet: int
    Colormap_Twilight: int
    Colormap_RdBu: int
    Colormap_BrBG: int
    Colormap_PiYG: int
    Colormap_Spectral: int
    Colormap_Greys: int
    # locations (ImPlotLocation)
    Location_Center: int
    Location_North: int
    Location_South: int
    Location_West: int
    Location_East: int
    Location_NorthWest: int
    Location_NorthEast: int
    Location_SouthWest: int
    Location_SouthEast: int
    # auto-binning methods (ImPlotBin)
    Bin_Sqrt: int
    Bin_Sturges: int
    Bin_Rice: int
    Bin_Scott: int

    # ── value structs ──
    class ImPlotPoint:
        x: float
        y: float
        def __init__(self, x: float = ..., y: float = ...) -> None: ...

    class ImPlotRange:
        min: float
        max: float
        def __init__(self, min: float = ..., max: float = ...) -> None: ...
        def size(self) -> float: ...
        def contains(self, value: float) -> bool: ...
        def clamp(self, value: float) -> float: ...

    class ImPlotRect:
        x: "_ImPlotModule.ImPlotRange"
        y: "_ImPlotModule.ImPlotRange"
        x_min: float
        x_max: float
        y_min: float
        y_max: float
        def __init__(self, x_min: float = ..., x_max: float = ..., y_min: float = ..., y_max: float = ...) -> None: ...

    class ImPlotSpec:
        line_color: _Col
        line_weight: float
        fill_color: _Col
        fill_alpha: float
        marker: int
        marker_size: float
        marker_line_color: _Col
        marker_fill_color: _Col
        size: float
        offset: int
        stride: int
        flags: int
        def __init__(self) -> None: ...

    class ImPlotStyle:
        plot_border_size: float
        minor_alpha: float
        digital_padding: float
        digital_spacing: float
        colormap: int
        use_local_time: bool
        use_iso_8601: bool
        use_24_hour_clock: bool
        plot_default_size: Tuple[float, float]
        plot_min_size: Tuple[float, float]
        major_tick_len: Tuple[float, float]
        minor_tick_len: Tuple[float, float]
        major_tick_size: Tuple[float, float]
        minor_tick_size: Tuple[float, float]
        major_grid_size: Tuple[float, float]
        minor_grid_size: Tuple[float, float]
        plot_padding: Tuple[float, float]
        label_padding: Tuple[float, float]
        legend_padding: Tuple[float, float]
        legend_inner_padding: Tuple[float, float]
        legend_spacing: Tuple[float, float]
        mouse_pos_padding: Tuple[float, float]
        annotation_padding: Tuple[float, float]
        fit_padding: Tuple[float, float]
        def get_color(self, idx: int) -> _Col: ...
        def set_color(self, idx: int, color: _Col) -> None: ...

    # ── spec builder ──
    def make_spec(self, line_col: Optional[_Col] = None, line_weight: float = 1.0, fill_col: Optional[_Col] = None, fill_alpha: float = 1.0, marker: int = ..., marker_size: float = 4.0, marker_line_col: Optional[_Col] = None, marker_fill_col: Optional[_Col] = None, size: float = 4.0, flags: int = 0) -> "_ImPlotModule.ImPlotSpec": ...

    # ── plot / subplot lifecycle (call end_* only when begin_* returns True) ──
    def begin_plot(self, title_id: str, width: float = -1.0, height: float = 0.0, flags: int = 0) -> bool: ...
    def end_plot(self) -> None: ...
    def begin_subplots(self, title_id: str, rows: int, cols: int, width: float, height: float, flags: int = 0, row_ratios: Optional[List[float]] = None, col_ratios: Optional[List[float]] = None) -> bool: ...
    def end_subplots(self) -> None: ...
    def begin_aligned_plots(self, group_id: str, vertical: bool = True) -> bool: ...
    def end_aligned_plots(self) -> None: ...

    # ── setup (after begin_plot, before item calls) ──
    def setup_axes(self, x_label: Optional[str] = None, y_label: Optional[str] = None, x_flags: int = 0, y_flags: int = 0) -> None: ...
    def setup_axis(self, axis: int, label: Optional[str] = None, flags: int = 0) -> None: ...
    def setup_axis_limits(self, axis: int, v_min: float, v_max: float, cond: int = ...) -> None: ...
    def setup_axes_limits(self, x_min: float, x_max: float, y_min: float, y_max: float, cond: int = ...) -> None: ...
    def setup_axis_format(self, axis: int, fmt: str) -> None: ...
    def setup_axis_scale(self, axis: int, scale: int) -> None: ...
    def setup_axis_ticks(self, axis: int, values: List[float], labels: List[str] = ..., keep_default: bool = False) -> None: ...
    def setup_axis_ticks_range(self, axis: int, v_min: float, v_max: float, n_ticks: int, labels: List[str] = ..., keep_default: bool = False) -> None: ...
    def setup_axis_limits_constraints(self, axis: int, v_min: float, v_max: float) -> None: ...
    def setup_axis_zoom_constraints(self, axis: int, z_min: float, z_max: float) -> None: ...
    def setup_legend(self, location: int, flags: int = 0) -> None: ...
    def setup_mouse_text(self, location: int, flags: int = 0) -> None: ...
    def setup_finish(self) -> None: ...
    def set_next_axis_limits(self, axis: int, v_min: float, v_max: float, cond: int = ...) -> None: ...
    def set_next_axis_to_fit(self, axis: int) -> None: ...
    def set_next_axes_limits(self, x_min: float, x_max: float, y_min: float, y_max: float, cond: int = ...) -> None: ...
    def set_next_axes_to_fit(self) -> None: ...

    # ── items (all styling via the optional spec) ──
    def plot_line(self, label: str, values: List[float], xscale: float = 1.0, xstart: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_line_xy(self, label: str, xs: List[float], ys: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_scatter(self, label: str, values: List[float], xscale: float = 1.0, xstart: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_scatter_xy(self, label: str, xs: List[float], ys: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_stairs(self, label: str, values: List[float], xscale: float = 1.0, xstart: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_stairs_xy(self, label: str, xs: List[float], ys: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_shaded(self, label: str, values: List[float], yref: float = 0.0, xscale: float = 1.0, xstart: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_shaded_xy(self, label: str, xs: List[float], ys: List[float], yref: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_shaded_between(self, label: str, xs: List[float], ys1: List[float], ys2: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_bars(self, label: str, values: List[float], bar_size: float = 0.67, shift: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_bars_xy(self, label: str, xs: List[float], ys: List[float], bar_size: float = 0.67, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_bar_groups(self, label_ids: List[str], values: List[float], item_count: int, group_count: int, group_size: float = 0.67, shift: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_error_bars(self, label: str, xs: List[float], ys: List[float], err: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_error_bars_asym(self, label: str, xs: List[float], ys: List[float], neg: List[float], pos: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_stems(self, label: str, values: List[float], ref: float = 0.0, scale: float = 1.0, start: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_stems_xy(self, label: str, xs: List[float], ys: List[float], ref: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_inf_lines(self, label: str, values: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_pie_chart(self, label_ids: List[str], values: List[float], x: float, y: float, radius: float, label_fmt: str = "%.1f", angle0: float = 90.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_heatmap(self, label: str, values: List[float], rows: int, cols: int, scale_min: float = 0.0, scale_max: float = 0.0, label_fmt: str = "%.1f", bounds_min_x: float = 0.0, bounds_min_y: float = 0.0, bounds_max_x: float = 1.0, bounds_max_y: float = 1.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_histogram(self, label: str, values: List[float], bins: int = ..., bar_scale: float = 1.0, range_min: float = 0.0, range_max: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> float: ...
    def plot_histogram_2d(self, label: str, xs: List[float], ys: List[float], x_bins: int = ..., y_bins: int = ..., x_min: float = 0.0, x_max: float = 0.0, y_min: float = 0.0, y_max: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> float: ...
    def plot_digital(self, label: str, xs: List[float], ys: List[float], spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_text(self, text: str, x: float, y: float, pix_offset_x: float = 0.0, pix_offset_y: float = 0.0, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...
    def plot_dummy(self, label: str, spec: "_ImPlotModule.ImPlotSpec" = ...) -> None: ...

    # ── plot utils / queries / coordinate conversion ──
    def set_axis(self, axis: int) -> None: ...
    def set_axes(self, x_axis: int, y_axis: int) -> None: ...
    def pixels_to_plot(self, x: float, y: float, x_axis: int = ..., y_axis: int = ...) -> "_ImPlotModule.ImPlotPoint": ...
    def plot_to_pixels(self, x: float, y: float, x_axis: int = ..., y_axis: int = ...) -> Tuple[float, float]: ...
    def get_plot_pos(self) -> Tuple[float, float]: ...
    def get_plot_size(self) -> Tuple[float, float]: ...
    def get_plot_mouse_pos(self, x_axis: int = ..., y_axis: int = ...) -> "_ImPlotModule.ImPlotPoint": ...
    def get_plot_limits(self, x_axis: int = ..., y_axis: int = ...) -> "_ImPlotModule.ImPlotRect": ...
    def is_plot_hovered(self) -> bool: ...
    def is_axis_hovered(self, axis: int) -> bool: ...
    def is_subplots_hovered(self) -> bool: ...
    def is_plot_selected(self) -> bool: ...
    def get_plot_selection(self, x_axis: int = ..., y_axis: int = ...) -> "_ImPlotModule.ImPlotRect": ...
    def cancel_plot_selection(self) -> None: ...
    def hide_next_item(self, hidden: bool = True, cond: int = ...) -> None: ...

    # ── legend utils ──
    def begin_legend_popup(self, label_id: str, mouse_button: int = 1) -> bool: ...
    def end_legend_popup(self) -> None: ...
    def is_legend_entry_hovered(self, label_id: str) -> bool: ...

    # ── drag tools — return (held, *new_values) ──
    def drag_point(self, id: int, x: float, y: float, col: _Col, size: float = 4.0, flags: int = 0) -> Tuple[bool, float, float]: ...
    def drag_line_x(self, id: int, x: float, col: _Col, thickness: float = 1.0, flags: int = 0) -> Tuple[bool, float]: ...
    def drag_line_y(self, id: int, y: float, col: _Col, thickness: float = 1.0, flags: int = 0) -> Tuple[bool, float]: ...
    def drag_rect(self, id: int, x1: float, y1: float, x2: float, y2: float, col: _Col, flags: int = 0) -> Tuple[bool, float, float, float, float]: ...

    # ── annotations & tags ──
    def annotation(self, x: float, y: float, col: _Col, off_x: float = 0.0, off_y: float = 0.0, clamp: bool = False, round: bool = False) -> None: ...
    def annotation_text(self, x: float, y: float, col: _Col, off_x: float, off_y: float, clamp: bool, text: str) -> None: ...
    def tag_x(self, x: float, col: _Col, round: bool = False) -> None: ...
    def tag_x_text(self, x: float, col: _Col, text: str) -> None: ...
    def tag_y(self, y: float, col: _Col, round: bool = False) -> None: ...
    def tag_y_text(self, y: float, col: _Col, text: str) -> None: ...

    # ── styling ──
    def get_style(self) -> "_ImPlotModule.ImPlotStyle": ...
    def style_colors_auto(self) -> None: ...
    def style_colors_classic(self) -> None: ...
    def style_colors_dark(self) -> None: ...
    def style_colors_light(self) -> None: ...
    def push_style_color(self, idx: int, col: _Col) -> None: ...
    def pop_style_color(self, count: int = 1) -> None: ...
    def push_style_var(self, idx: int, val: float) -> None: ...
    def push_style_var_int(self, idx: int, val: int) -> None: ...
    def push_style_var_vec2(self, idx: int, x: float, y: float) -> None: ...
    def pop_style_var(self, count: int = 1) -> None: ...
    def get_style_color_name(self, idx: int) -> str: ...
    def get_marker_name(self, idx: int) -> str: ...

    # ── colormaps ──
    def add_colormap(self, name: str, colors: List[_Col], qual: bool = True) -> int: ...
    def get_colormap_count(self) -> int: ...
    def get_colormap_name(self, cmap: int) -> str: ...
    def get_colormap_index(self, name: str) -> int: ...
    def push_colormap(self, cmap: int) -> None: ...
    def push_colormap_by_name(self, name: str) -> None: ...
    def pop_colormap(self, count: int = 1) -> None: ...
    def next_colormap_color(self) -> _Col: ...
    def get_colormap_size(self, cmap: int = ...) -> int: ...
    def get_colormap_color(self, idx: int, cmap: int = ...) -> _Col: ...
    def sample_colormap(self, t: float, cmap: int = ...) -> _Col: ...
    def colormap_scale(self, label: str, scale_min: float, scale_max: float, width: float = 0.0, height: float = 0.0, format: str = "%g", flags: int = 0, cmap: int = ...) -> None: ...
    def colormap_slider(self, label: str, t: float, format: str = "", cmap: int = ...) -> Tuple[bool, float, _Col]: ...
    def colormap_button(self, label: str, width: float = 0.0, height: float = 0.0, cmap: int = ...) -> bool: ...

    # ── demo / diagnostics ──
    def show_demo_window(self) -> None: ...
    def show_metrics_window(self) -> None: ...
    def show_style_editor(self) -> None: ...
    def show_user_guide(self) -> None: ...
    def show_style_selector(self, label: str) -> bool: ...
    def show_colormap_selector(self, label: str) -> bool: ...
    def bust_color_cache(self) -> None: ...

implot: _ImPlotModule
