# PyImGui stub — Reforged Native surface (2026-07-06)
# Matches imgui_bindings.cpp + sub-module registrars (types, enums, style, docking, drawlist, io, addons).
# ImGui 1.92.x docking branch. Full parity with legacy API surface preserved.

from typing import Optional, Tuple, List, Any, overload
from enum import Enum, IntEnum

# ═══════════════ TYPES ═══════════════════════════════════
class Vec2:
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

class Vec4:
    x: float
    y: float
    z: float
    w: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 0.0) -> None: ...

class StyleConfig:
    """Live mutable view of the current ImGuiStyle."""
    Alpha: float
    DisabledAlpha: float
    WindowPadding: Vec2
    WindowRounding: float
    WindowBorderSize: float
    WindowMinSize: Vec2
    WindowTitleAlign: Vec2
    ChildRounding: float
    ChildBorderSize: float
    PopupRounding: float
    PopupBorderSize: float
    FramePadding: Vec2
    FrameRounding: float
    FrameBorderSize: float
    ItemSpacing: Vec2
    ItemInnerSpacing: Vec2
    CellPadding: Vec2
    TouchExtraPadding: Vec2
    IndentSpacing: float
    ColumnsMinSpacing: float
    ScrollbarSize: float
    ScrollbarRounding: float
    GrabMinSize: float
    GrabRounding: float
    TabRounding: float
    TabBorderSize: float
    TabBarBorderSize: float
    TabMinWidthForCloseButton: float
    TableAngledHeadersAngle: float
    ColorButtonPosition: int
    ButtonTextAlign: Vec2
    SelectableTextAlign: Vec2
    SeparatorTextBorderSize: float
    SeparatorTextAlign: Vec2
    SeparatorTextPadding: Vec2
    DisplayWindowPadding: Vec2
    DisplaySafeAreaPadding: Vec2
    MouseCursorScale: float
    AntiAliasedLines: bool
    AntiAliasedLinesUseTex: bool
    AntiAliasedFill: bool
    CurveTessellationTol: float
    CircleTessellationMaxError: float
    @property
    def Colors(self) -> List[Vec4]: ...

def get_style() -> StyleConfig: ...

class SortDirection(IntEnum):
    NoDirection = 0
    Ascending = 1
    Descending = 2

class TableColumnSortSpecs:
    @property
    def ColumnIndex(self) -> int: ...
    @property
    def SortDirection(self) -> SortDirection: ...

class TableSortSpecs:
    @property
    def SpecsCount(self) -> int: ...
    @property
    def SpecsDirty(self) -> bool: ...
    @property
    def Specs(self) -> Optional[TableColumnSortSpecs]: ...

class DrawList:
    """ImDrawList wrapper — obtain via get_window_draw_list() / get_foreground_draw_list() / get_background_draw_list()."""
    def add_line(self, p1: Tuple[float, float], p2: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
    def add_rect(self, p_min: Tuple[float, float], p_max: Tuple[float, float], col: int, rounding: float = 0.0, flags: int = 0, thickness: float = 1.0) -> None: ...
    def add_rect_filled(self, p_min: Tuple[float, float], p_max: Tuple[float, float], col: int, rounding: float = 0.0, flags: int = 0) -> None: ...
    def add_circle(self, center: Tuple[float, float], radius: float, col: int, num_segments: int = 0, thickness: float = 1.0) -> None: ...
    def add_circle_filled(self, center: Tuple[float, float], radius: float, col: int, num_segments: int = 0) -> None: ...
    def add_text(self, pos: Tuple[float, float], col: int, text: str) -> None: ...
    def add_triangle(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
    def add_triangle_filled(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int) -> None: ...
    def add_quad(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
    def add_quad_filled(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int) -> None: ...
    def add_polyline(self, points: List[Tuple[float, float]], col: int, flags: int = 0, thickness: float = 1.0) -> None: ...
    def add_convex_poly_filled(self, points: List[Tuple[float, float]], col: int) -> None: ...
    def add_bezier_cubic(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int, thickness: float = 1.0, num_segments: int = 0) -> None: ...
    def add_bezier_quadratic(self, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int, thickness: float = 1.0, num_segments: int = 0) -> None: ...
    def path_clear(self) -> None: ...
    def path_line_to(self, pos: Tuple[float, float]) -> None: ...
    def path_fill_convex(self, col: int) -> None: ...
    def path_stroke(self, col: int, flags: int = 0, thickness: float = 1.0) -> None: ...
    def path_arc_to(self, center: Tuple[float, float], radius: float, a_min: float, a_max: float, num_segments: int = 0) -> None: ...
    def path_arc_to_fast(self, center: Tuple[float, float], radius: float, a_min: int, a_max: int) -> None: ...
    def path_bezier_cubic_curve_to(self, p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], num_segments: int = 0) -> None: ...
    def path_bezier_quadratic_curve_to(self, p2: Tuple[float, float], p3: Tuple[float, float], num_segments: int = 0) -> None: ...
    def path_rect(self, rect_min: Tuple[float, float], rect_max: Tuple[float, float], rounding: float = 0.0, flags: int = 0) -> None: ...
    def add_image(self, tex_id: int, p_min: Tuple[float, float], p_max: Tuple[float, float], uv_min: Tuple[float, float] = (0,0), uv_max: Tuple[float, float] = (1,1), col: int = 0xFFFFFFFF) -> None: ...
    def add_image_rounded(self, tex_id: int, p_min: Tuple[float, float], p_max: Tuple[float, float], uv_min: Tuple[float, float], uv_max: Tuple[float, float], col: int, rounding: float, flags: int = 0) -> None: ...
    def add_image_quad(self, tex_id: int, p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], uv1: Tuple[float, float] = (0,0), uv2: Tuple[float, float] = (1,0), uv3: Tuple[float, float] = (1,1), uv4: Tuple[float, float] = (0,1), col: int = 0xFFFFFFFF) -> None: ...
    def prim_reserve(self, idx_count: int, vtx_count: int) -> None: ...
    def prim_quad_uv(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], d: Tuple[float, float], uv_a: Tuple[float, float], uv_b: Tuple[float, float], uv_c: Tuple[float, float], uv_d: Tuple[float, float], col: int) -> None: ...
    def prim_rect(self, a: Tuple[float, float], b: Tuple[float, float], col: int) -> None: ...
    def prim_rect_uv(self, a: Tuple[float, float], b: Tuple[float, float], uv_a: Tuple[float, float], uv_b: Tuple[float, float], col: int) -> None: ...
    def push_clip_rect(self, clip_rect_min: Tuple[float, float], clip_rect_max: Tuple[float, float], intersect: bool = False) -> None: ...
    def push_clip_rect_full_screen(self) -> None: ...
    def pop_clip_rect(self) -> None: ...
    def push_texture_id(self, texture_id: int) -> None: ...
    def pop_texture_id(self) -> None: ...
    def get_clip_rect_min(self) -> Tuple[float, float]: ...
    def get_clip_rect_max(self) -> Tuple[float, float]: ...

def get_window_draw_list() -> DrawList: ...
def get_foreground_draw_list() -> DrawList: ...
def get_background_draw_list() -> DrawList: ...

# Flat draw_list functions (legacy surface — each operates on GetWindowDrawList())
def draw_list_add_line(p1: Tuple[float, float], p2: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
def draw_list_add_rect(p_min: Tuple[float, float], p_max: Tuple[float, float], col: int, rounding: float = 0.0, thickness: float = 1.0) -> None: ...
def draw_list_add_rect_filled(p_min: Tuple[float, float], p_max: Tuple[float, float], col: int, rounding: float = 0.0) -> None: ...
def draw_list_add_circle(center: Tuple[float, float], radius: float, col: int, num_segments: int = 0, thickness: float = 1.0) -> None: ...
def draw_list_add_circle_filled(center: Tuple[float, float], radius: float, col: int, num_segments: int = 0) -> None: ...
def draw_list_add_text(pos: Tuple[float, float], col: int, text: str) -> None: ...
def draw_list_add_triangle(p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
def draw_list_add_triangle_filled(p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], col: int) -> None: ...
def draw_list_add_quad(p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int, thickness: float = 1.0) -> None: ...
def draw_list_add_quad_filled(p1: Tuple[float, float], p2: Tuple[float, float], p3: Tuple[float, float], p4: Tuple[float, float], col: int) -> None: ...

# IO access
def get_io() -> Any: ...

# ═══════════════ WINDOW ═══════════════════════════════════
def begin(name: str, *args) -> bool:
    """Overloads: (name) / (name, flags) / (name, p_open, flags). Returns visible bool."""
    ...
def end() -> None: ...
def begin_with_close(name: str, p_open: bool, flags: int = 0) -> Tuple[bool, bool]: ...
def begin_child(id: str, size: Tuple[float, float] = (0,0), border: int = 0, flags: int = 0) -> bool: ...
def end_child() -> None: ...
def begin_group() -> None: ...
def end_group() -> None: ...
def begin_disabled(disabled: bool = True) -> None: ...
def end_disabled() -> None: ...

# Window setup
def set_next_window_pos(x: float, y: float, cond: int = 0) -> None: ...
def set_next_window_size(width: float, height: float, cond: int = 0) -> None: ...
def set_next_window_size_constraints(size_min: Tuple[float, float], size_max: Tuple[float, float]) -> None: ...
def set_next_window_content_size(size: Tuple[float, float]) -> None: ...
def set_next_window_collapsed(collapsed: bool, cond: int = 0) -> None: ...
def set_next_window_focus() -> None: ...
def set_next_window_bg_alpha(alpha: float) -> None: ...
def set_next_window_scroll(scroll: Tuple[float, float]) -> None: ...
def set_next_window_viewport(viewport_id: int) -> None: ...
def set_window_pos(x: float, y: float, cond: int = 0) -> None: ...
def set_window_size(width: float, height: float, cond: int = 0) -> None: ...
def set_window_collapsed(collapsed: bool, cond: int = 0) -> None: ...
def set_window_focus(name: str) -> None: ...

# Window query
def get_window_pos() -> Tuple[float, float]: ...
def get_window_size() -> Tuple[float, float]: ...
def get_window_width() -> float: ...
def get_window_height() -> float: ...
def get_content_region_avail() -> Tuple[float, float]: ...
def is_window_appearing() -> bool: ...
def is_window_collapsed() -> bool: ...
def is_window_focused(flags: int = 0) -> bool: ...
def is_window_hovered(flags: int = 0) -> bool: ...
def is_rect_visible(size: Tuple[float, float]) -> bool: ...

# ═══════════════ LAYOUT ═══════════════════════════════════
def separator() -> None: ...
def separator_text(label: str) -> None: ...
def same_line(offset_from_start_x: float = 0.0, spacing: float = -1.0) -> None: ...
def spacing() -> None: ...
def new_line() -> None: ...
def dummy(size: Tuple[float, float]) -> None: ...
def indent(indent_w: float = 0.0) -> None: ...
def unindent(indent_w: float = 0.0) -> None: ...
def align_text_to_frame_padding() -> None: ...
def get_frame_height() -> float: ...
def get_frame_height_with_spacing() -> float: ...
def get_font_size() -> float: ...

# Font switching
def push_font(font_index: int = 0) -> None: ...
def pop_font() -> None: ...
def push_font_scaled(font_index: int, scale: float = 1.0) -> None: ...
def pop_font_scaled() -> None: ...

# ═══════════════ TEXT ═══════════════════════════════════
def text_unformatted(text: str) -> None: ...
def text_link(label: str) -> bool: ...
def text_link_open_url(label: str, url: str = None) -> bool: ...
def text(text: str) -> None: ...
def text_colored(*args) -> None:
    """Overloads: (color, text) / (r, g, b, a, text) / (text, color)."""
    ...
def text_disabled(text: str) -> None: ...
def text_wrapped(text: str) -> None: ...
def bullet_text(text: str) -> None: ...
def label_text(label: str, text: str) -> None: ...

# ═══════════════ WIDGETS ════════════════════════════════
def button(label: str, *args) -> bool:
    """Overloads: (label) / (label, size) / (label, width, height)."""
    ...
def small_button(label: str) -> bool: ...
def invisible_button(str_id: str, size: Tuple[float, float], flags: int = 0) -> bool: ...
def arrow_button(str_id: str, dir: int) -> bool: ...
def checkbox(label: str, value: bool) -> bool: ...
def radio_button(label: str, value: int, v_button: int) -> int: ...
def progress_bar(fraction: float, size_arg_x: float = -1.0, size_arg_y: float = 0.0, overlay: str = None) -> None: ...
def bullet() -> None: ...
def checkbox_flags(label: str, flags: int, flags_value: int) -> int: ...

# Sliders
def slider_float(label: str, v: float, v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> float: ...
def slider_int(label: str, v: int, v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> int: ...
def slider_angle(label: str, v_rad: float, v_degrees_min: float = -360.0, v_degrees_max: float = 360.0, format: str = "%.0f deg", flags: int = 0) -> float: ...
def v_slider_float(label: str, size: Tuple[float, float], v: float, v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> float: ...
def v_slider_int(label: str, size: Tuple[float, float], v: int, v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> int: ...
def slider_float2(label: str, v: Tuple[float, float], v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> Tuple[float, float]: ...
def slider_float3(label: str, v: Tuple[float, float, float], v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float]: ...
def slider_float4(label: str, v: Tuple[float, float, float, float], v_min: float, v_max: float, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float, float]: ...
def slider_int2(label: str, v: Tuple[int, int], v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> Tuple[int, int]: ...
def slider_int3(label: str, v: Tuple[int, int, int], v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> Tuple[int, int, int]: ...
def slider_int4(label: str, v: Tuple[int, int, int, int], v_min: int, v_max: int, format: str = "%d", flags: int = 0) -> Tuple[int, int, int, int]: ...

# Drags
def drag_float(label: str, v: float, v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> float: ...
def drag_float_range2(label: str, v_current_min: float, v_current_max: float, v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", format_max: str = None, flags: int = 0) -> Tuple[float, float]: ...
def drag_int(label: str, v: int, v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> int: ...
def drag_int_range2(label: str, v_current_min: int, v_current_max: int, v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", format_max: str = None, flags: int = 0) -> Tuple[int, int]: ...
def drag_float2(label: str, v: Tuple[float, float], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> Tuple[float, float]: ...
def drag_float3(label: str, v: Tuple[float, float, float], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float]: ...
def drag_float4(label: str, v: Tuple[float, float, float, float], v_speed: float = 1.0, v_min: float = 0.0, v_max: float = 0.0, format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float, float]: ...
def drag_int2(label: str, v: Tuple[int, int], v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> Tuple[int, int]: ...
def drag_int3(label: str, v: Tuple[int, int, int], v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> Tuple[int, int, int]: ...
def drag_int4(label: str, v: Tuple[int, int, int, int], v_speed: float = 1.0, v_min: int = 0, v_max: int = 0, format: str = "%d", flags: int = 0) -> Tuple[int, int, int, int]: ...

# ═══════════════ INPUT ═══════════════════════════════════
def input_float(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = "%.3f", flags: int = 0) -> float: ...
def input_float2(label: str, v: Tuple[float, float], format: str = "%.3f", flags: int = 0) -> Tuple[float, float]: ...
def input_float3(label: str, v: Tuple[float, float, float], format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float]: ...
def input_float4(label: str, v: Tuple[float, float, float, float], format: str = "%.3f", flags: int = 0) -> Tuple[float, float, float, float]: ...
def input_int(label: str, v: int, step: int = 1, step_fast: int = 100, flags: int = 0) -> int: ...
def input_int2(label: str, v: Tuple[int, int], flags: int = 0) -> Tuple[int, int]: ...
def input_int3(label: str, v: Tuple[int, int, int], flags: int = 0) -> Tuple[int, int, int]: ...
def input_int4(label: str, v: Tuple[int, int, int, int], flags: int = 0) -> Tuple[int, int, int, int]: ...
def input_double(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = "%.6f", flags: int = 0) -> float: ...
def input_text(label: str, text: str = "", flags: int = 0) -> str: ...
def input_text_with_hint(label: str, hint: str, text: str = "", flags: int = 0) -> str: ...
def input_text_multiline(label: str, text: str = "", size: Tuple[float, float] = (0,0), flags: int = 0) -> str: ...

# Combo / List box
def begin_combo(label: str, preview_value: str, flags: int = 0) -> bool: ...
def end_combo() -> None: ...
def combo(label: str, current_item: int, items: List[str]) -> int: ...
def begin_list_box(label: str, size: Tuple[float, float] = (0,0)) -> bool: ...
def end_list_box() -> None: ...
def list_box(label: str, current_item: int, items: List[str], height_in_items: int = -1) -> int: ...

# Selectable
def selectable(label: str, selected: bool = False, flags: int = 0, size: Tuple[float, float] = (0,0)) -> bool: ...

# ═══════════════ COLOR ═══════════════════════════════════
def color_edit3(label: str, col: Tuple[float, float, float], flags: int = 0) -> Tuple[float, float, float]: ...
def color_edit4(label: str, col: Tuple[float, float, float, float], flags: int = 0) -> Tuple[float, float, float, float]: ...
def color_picker3(label: str, col: Tuple[float, float, float], flags: int = 0) -> Tuple[float, float, float]: ...
def color_picker4(label: str, col: Tuple[float, float, float, float], flags: int = 0) -> Tuple[float, float, float, float]: ...
def color_button(desc_id: str, col: Tuple[float, float, float, float], flags: int = 0, size: Tuple[float, float] = (0,0)) -> bool: ...
def set_color_edit_options(flags: int) -> None: ...
def color_convert_u32_to_float4(in_: int) -> Tuple[float, float, float, float]: ...
def color_convert_float4_to_u32(in_: Tuple[float, float, float, float]) -> int: ...
def color_convert_rgb_to_hsv(r: float, g: float, b: float) -> Tuple[float, float, float]: ...
def color_convert_hsv_to_rgb(h: float, s: float, v: float) -> Tuple[float, float, float]: ...
def get_color_u32(idx: int, alpha_mul: float = 1.0) -> int: ...
def get_color_u32_vec4(col: Tuple[float, float, float, float]) -> int: ...
def get_style_color_vec4(idx: int) -> Tuple[float, float, float, float]: ...

# ═══════════════ IMAGE ═══════════════════════════════════
def image(tex_id: int, size: Tuple[float, float], uv0: Tuple[float, float] = (0,0), uv1: Tuple[float, float] = (1,1)) -> None: ...
def image_with_bg(tex_id: int, size: Tuple[float, float], uv0: Tuple[float, float] = (0,0), uv1: Tuple[float, float] = (1,1), bg_col: Tuple[float, float, float, float] = (0,0,0,0), tint_col: Tuple[float, float, float, float] = (1,1,1,1)) -> None: ...
def image_button(str_id: str, tex_id: int, size: Tuple[float, float], uv0: Tuple[float, float] = (0,0), uv1: Tuple[float, float] = (1,1), bg_col: Tuple[float, float, float, float] = (0,0,0,0), tint_col: Tuple[float, float, float, float] = (1,1,1,1)) -> bool: ...

# ═══════════════ TREE / COLLAPSING ═══════════════════════
def tree_node(label: str) -> bool: ...
def tree_node_ex(label: str, flags: int = 0) -> bool: ...
def tree_pop() -> None: ...
def tree_push(str_id: str) -> None: ...
def tree_push_ptr(ptr_id: int) -> None: ...
def get_tree_node_to_label_spacing() -> float: ...
def set_next_item_open(is_open: bool, cond: int = 0) -> None: ...
def set_next_item_storage_id(storage_id: int) -> None: ...
def tree_node_get_open(storage_id: int) -> bool: ...
def collapsing_header(label: str, flags: int = 0) -> bool: ...

# ═══════════════ TABS ═══════════════════════════════════
def begin_tab_bar(str_id: str, flags: int = 0) -> bool: ...
def end_tab_bar() -> None: ...
def begin_tab_item(label: str, p_open: bool = None, flags: int = 0) -> bool: ...
def begin_tab_item_closable(label: str, p_open: bool = True, flags: int = 0) -> Tuple[bool, bool]: ...
def end_tab_item() -> None: ...
def tab_item_button(label: str, flags: int = 0) -> bool: ...
def set_tab_item_closed(tab_or_docked_window_label: str) -> None: ...

# ═══════════════ TABLES ═══════════════════════════════════
def begin_table(str_id: str, column: int, flags: int = 0, *args) -> bool:
    """Overloads: (id, cols, flags, outer_size, inner_width) / (id, cols, flags, width, height)."""
    ...
def end_table() -> None: ...
def table_next_row(row_flags: int = 0, min_row_height: float = 0.0) -> None: ...
def table_next_column() -> bool: ...
def table_set_column_index(column_n: int) -> bool: ...
def table_setup_column(label: str, flags: int = 0, init_width_or_weight: float = 0.0, user_id: int = 0) -> None: ...
def table_setup_scroll_freeze(cols: int, rows: int) -> None: ...
def table_headers_row() -> None: ...
def table_header(label: str) -> None: ...
def table_angled_headers_row() -> None: ...
def table_get_column_count() -> int: ...
def table_get_column_index() -> int: ...
def table_get_row_index() -> int: ...
def table_get_column_name(column_n: int = -1) -> str: ...
def table_get_column_flags(column_n: int = -1) -> int: ...
def table_get_hovered_column() -> int: ...
def table_set_column_enabled(column_n: int, v: bool) -> None: ...
def table_set_bg_color(target: int, color: int, column_n: int = -1) -> None: ...
def table_get_sort_specs() -> Optional[TableSortSpecs]: ...
def clear_sort_specs_dirty() -> None: ...

# Legacy columns
def columns(count: int = 1, id: str = None, borders: bool = True) -> None: ...
def next_column() -> None: ...
def end_columns() -> None: ...
def set_column_width(column_index: int, width: float) -> None: ...
def set_column_offset(column_index: int, offset_x: float) -> None: ...
def get_column_index() -> int: ...
def get_column_width(column_index: int = -1) -> float: ...
def get_column_offset(column_index: int = -1) -> float: ...
def get_columns_count() -> int: ...

# ═══════════════ MENUS ═══════════════════════════════════
def begin_menu_bar() -> bool: ...
def end_menu_bar() -> None: ...
def begin_main_menu_bar() -> bool: ...
def end_main_menu_bar() -> None: ...
def begin_menu(label: str, enabled: bool = True) -> bool: ...
def end_menu() -> None: ...
def menu_item(label: str, shortcut: str = None, selected: bool = False, enabled: bool = True) -> bool: ...

# ═══════════════ POPUPS / TOOLTIPS ═══════════════════════
def open_popup(str_id: str, popup_flags: int = 0) -> None: ...
def open_popup_on_item_click(str_id: str = None, popup_flags: int = 0) -> None: ...
def begin_popup(str_id: str, flags: int = 0) -> bool: ...
def end_popup() -> None: ...
def end_popup_modal() -> None: ...
def begin_popup_modal(name: str, p_open: bool = None, flags: int = 0) -> bool: ...
def close_current_popup() -> None: ...
def begin_popup_context_item(str_id: str = None, popup_flags: int = 0) -> bool: ...
def begin_popup_context_window(str_id: str = None, popup_flags: int = 0) -> bool: ...
def begin_popup_context_void(str_id: str = None, popup_flags: int = 0) -> bool: ...
def is_popup_open(str_id: str, flags: int = 0) -> bool: ...
def begin_tooltip() -> None: ...
def end_tooltip() -> None: ...
def set_tooltip(fmt: str) -> None: ...
def show_tooltip(text: str) -> None: ...
def begin_item_tooltip() -> None: ...
def set_item_tooltip(fmt: str) -> None: ...

# ═══════════════ CURSOR ═══════════════════════════════════
def get_cursor_pos() -> Tuple[float, float]: ...
def set_cursor_pos(local_pos: Tuple[float, float]) -> None: ...
def get_cursor_pos_x() -> float: ...
def set_cursor_pos_x(local_x: float) -> None: ...
def get_cursor_pos_y() -> float: ...
def set_cursor_pos_y(local_y: float) -> None: ...
def get_cursor_screen_pos() -> Tuple[float, float]: ...
def set_cursor_screen_pos(pos: Tuple[float, float]) -> None: ...
def get_cursor_start_pos() -> Tuple[float, float]: ...

# ═══════════════ SCROLLING ═══════════════════════════════
def get_scroll_x() -> float: ...
def get_scroll_y() -> float: ...
def get_scroll_max_x() -> float: ...
def get_scroll_max_y() -> float: ...
def set_scroll_x(scroll_x: float) -> None: ...
def set_scroll_y(scroll_y: float) -> None: ...
def set_scroll_here_x(center_x_ratio: float = 0.5) -> None: ...
def set_scroll_here_y(center_y_ratio: float = 0.5) -> None: ...
def set_scroll_from_pos_x(local_x: float, center_x_ratio: float = 0.5) -> None: ...
def set_scroll_from_pos_y(local_y: float, center_y_ratio: float = 0.5) -> None: ...

# ═══════════════ ITEM QUERY ═══════════════════════════════
def is_item_hovered(flags: int = 0) -> bool: ...
def is_item_active() -> bool: ...
def is_item_focused() -> bool: ...
def is_item_clicked(mouse_button: int = 0) -> bool: ...
def is_item_visible() -> bool: ...
def is_item_edited() -> bool: ...
def is_item_activated() -> bool: ...
def is_item_deactivated() -> bool: ...
def is_item_deactivated_after_edit() -> bool: ...
def is_item_toggled_open() -> bool: ...
def is_any_item_hovered() -> bool: ...
def is_any_item_active() -> bool: ...
def is_any_item_focused() -> bool: ...
def get_item_id() -> int: ...
def get_item_rect_min() -> Tuple[float, float]: ...
def get_item_rect_max() -> Tuple[float, float]: ...
def get_item_rect_size() -> Tuple[float, float]: ...
def get_item_flags() -> int: ...
def set_item_default_focus() -> None: ...
def set_nav_cursor_visible(visible: bool) -> None: ...
def set_next_item_width(item_width: float) -> None: ...
def set_next_item_allow_overlap() -> None: ...

# ═══════════════ ID / FOCUS ═══════════════════════════════
def push_id(str_id: str) -> None: ...
def push_id_int(int_id: int) -> None: ...
def pop_id() -> None: ...
def get_id(str_id: str) -> int: ...
def get_id_int(int_id: int) -> int: ...
def set_keyboard_focus_here(offset: int = 0) -> None: ...

# ═══════════════ KEYBOARD ═══════════════════════════════
def is_key_down(key: int) -> bool: ...
def is_key_pressed(key: int, repeat: bool = True) -> bool: ...
def is_key_released(key: int) -> bool: ...
def is_key_chord_pressed(key_chord: int) -> bool: ...
def get_key_name(key: int) -> str: ...
def get_key_pressed_amount(key: int, repeat_delay: float, rate: float) -> int: ...
def set_next_frame_want_capture_keyboard(want_capture_keyboard: bool) -> None: ...
def shortcut(key_chord: int, flags: int = 0) -> bool: ...
def set_next_item_shortcut(key_chord: int, flags: int = 0) -> None: ...
def set_item_key_owner(key: int) -> None: ...

# ═══════════════ MOUSE ═══════════════════════════════════
def set_mouse_cursor(cursor_type: int) -> None: ...
def get_mouse_cursor() -> int: ...
def get_mouse_pos() -> Tuple[float, float]: ...
def get_mouse_pos_on_opening_current_popup() -> Tuple[float, float]: ...
def is_mouse_down(button: int) -> bool: ...
def is_mouse_clicked(button: int, repeat: bool = False) -> bool: ...
def is_mouse_released(button: int) -> bool: ...
def is_mouse_double_clicked(button: int) -> bool: ...
def is_mouse_released_with_delay(button: int, delay: float) -> bool: ...
def is_mouse_dragging(button: int, lock_threshold: float = -1.0) -> bool: ...
def is_mouse_hovering_rect(r_min: Tuple[float, float], r_max: Tuple[float, float], clip: bool = True) -> bool: ...
def is_any_mouse_down() -> bool: ...
def is_mouse_pos_valid(mouse_pos: Tuple[float, float] = (-3.4028235e38, -3.4028235e38)) -> bool: ...
def get_mouse_clicked_count(button: int) -> int: ...
def get_mouse_drag_delta(button: int = 0, lock_threshold: float = -1.0) -> Tuple[float, float]: ...
def reset_mouse_drag_delta(button: int = 0) -> None: ...
def set_next_frame_want_capture_mouse(want_capture_mouse: bool) -> None: ...

# ═══════════════ STYLE ═══════════════════════════════════
def push_style_color(idx: int, col: Tuple[float, float, float, float]) -> None: ...
def push_style_color_u32(idx: int, col_u32: int) -> None: ...
def pop_style_color(count: int = 1) -> None: ...
def push_style_var(idx: int, val: float) -> None: ...
def push_style_var_vec2(idx: int, val: Tuple[float, float]) -> None: ...
def push_style_var_x(idx: int, val_x: float) -> None: ...
def push_style_var_y(idx: int, val_y: float) -> None: ...
def pop_style_var(count: int = 1) -> None: ...
def push_item_flag(option: int, enabled: bool) -> None: ...
def pop_item_flag() -> None: ...
def push_item_width(item_width: float) -> None: ...
def pop_item_width() -> None: ...
def calc_item_width() -> float: ...
def push_text_wrap_pos(wrap_local_pos_x: float = 0.0) -> None: ...
def pop_text_wrap_pos() -> None: ...
def push_button_repeat(repeat: bool) -> None: ...
def pop_button_repeat() -> None: ...
def style_colors_dark(dst=None) -> None: ...
def style_colors_light(dst=None) -> None: ...
def style_colors_classic(dst=None) -> None: ...
def get_style_color_name(idx: int) -> str: ...

# ═══════════════ CLIP RECT ═══════════════════════════════
def push_clip_rect(*args) -> None:
    """Overloads: (clip_rect_min, clip_rect_max, intersect) / (x, y, width, height, intersect)."""
    ...
def pop_clip_rect() -> None: ...

# ═══════════════ FONT ═══════════════════════════════════
def get_text_line_height() -> float: ...
def get_text_line_height_with_spacing() -> float: ...
def calc_text_size(text: str, text_end: str = None, hide_text_after_double_hash: bool = False, wrap_width: float = -1.0) -> Tuple[float, float]: ...
def get_font() -> Any: ...
def get_font_tex_uv_white_pixel() -> Tuple[float, float]: ...
def set_window_font_scale(s: float) -> None: ...

# ═══════════════ CLIPBOARD / LOG ═════════════════════════
def get_clipboard_text() -> str: ...
def set_clipboard_text(text: str) -> None: ...
def log_to_tty(auto_open_depth: int = -1) -> None: ...
def log_to_file(auto_open_depth: int = -1, filename: str = None) -> None: ...
def log_to_clipboard(auto_open_depth: int = -1) -> None: ...
def log_buttons() -> None: ...
def log_finish() -> None: ...
def get_time() -> float: ...
def get_frame_count() -> int: ...

# ═══════════════ INI ═══════════════════════════════════
def load_ini_settings_from_disk(ini_filename: str) -> None: ...
def load_ini_settings_from_memory(ini_data: str, ini_size: int = 0) -> None: ...
def save_ini_settings_to_disk(ini_filename: str) -> None: ...
def save_ini_settings_to_memory() -> str: ...

# ═══════════════ DRAG & DROP ═══════════════════════════
def begin_drag_drop_source(flags: int = 0) -> bool: ...
def set_drag_drop_payload(type: str, data: Any, sz: int, cond: int = 0) -> bool: ...
def end_drag_drop_source() -> None: ...
def begin_drag_drop_target() -> bool: ...
def accept_drag_drop_payload(type: str, flags: int = 0) -> Any: ...
def end_drag_drop_target() -> None: ...
def get_drag_drop_payload() -> Any: ...

# ═══════════════ VIEWPORT ═══════════════════════════════
def get_main_viewport() -> Any: ...
def get_window_viewport() -> Any: ...
def get_window_dpi_scale() -> float: ...

# ═══════════════ PLOTTING ═══════════════════════════════
def plot_lines(label: str, values: List[float], values_offset: int = 0, overlay_text: str = None, scale_min: float = 3.4028235e38, scale_max: float = 3.4028235e38, graph_size: Tuple[float, float] = (0,0)) -> None: ...
def plot_histogram(label: str, values: List[float], values_offset: int = 0, overlay_text: str = None, scale_min: float = 3.4028235e38, scale_max: float = 3.4028235e38, graph_size: Tuple[float, float] = (0,0)) -> None: ...
def value_bool(prefix: str, v: bool) -> None: ...
def value_int(prefix: str, v: int) -> None: ...
def value_uint(prefix: str, v: int) -> None: ...
def value_float(prefix: str, v: float, float_format: str = None) -> None: ...

# ═══════════════ DEBUG ═══════════════════════════════════
def show_demo_window() -> None: ...
def show_metrics_window() -> None: ...
def show_debug_log_window() -> None: ...
def show_id_stack_tool_window() -> None: ...
def show_about_window() -> None: ...
def show_style_editor() -> None: ...
def show_style_selector(label: str) -> None: ...
def show_font_selector(label: str) -> None: ...
def show_user_guide() -> None: ...
def get_version() -> str: ...
def debug_flash_style_color(idx: int) -> None: ...
def debug_start_item_picker() -> None: ...
def debug_text_encoding(text: str) -> None: ...

# ═══════════════ DOCKING (sub-module) ═══════════════════
def dock_space(id: int, size: Tuple[float, float] = (0,0), flags: int = 0) -> int: ...
def dock_space_over_viewport(viewport=None, flags: int = 0) -> int: ...
def dock_builder_add_node(id: int, flags: int = 0) -> int: ...
def dock_builder_remove_node(id: int) -> None: ...
def dock_builder_set_node_pos(id: int, pos: Tuple[float, float]) -> None: ...
def dock_builder_set_node_size(id: int, size: Tuple[float, float]) -> None: ...
def dock_builder_split_node(id: int, split_dir: int, size_ratio_for_node_at_dir: float, out_id_at_dir: int, out_id_at_opposite_dir: int) -> int: ...
def dock_builder_dock_window(window_name: str, node_id: int) -> None: ...
def dock_builder_finish(id: int) -> None: ...
def dock_builder_get_node(id: int) -> Any: ...
def dock_builder_get_central_node(id: int) -> int: ...
def dock_builder_copy_dock_space(src_dockspace_id: int, dst_dockspace_id: int) -> None: ...
def dock_builder_remove_node_docked_windows(id: int, clear_settings_refs: bool = True) -> None: ...
def dock_builder_remove_node_child_nodes(id: int) -> None: ...

# ═══════════════ ADDONS (sub-module) ═══════════════════
# PyImGui.filebrowser — FileBrowser class
# PyImGui.hotkey — Hotkey class
# PyImGui.markdown — Markdown rendering
# PyImGui.memory_editor — MemoryEditor class
# PyImGui.anim — Animation helpers
