# PyKeystroke stub — Reforged Native surface (2026-07-06)
# Matches virtual_input_bindings.cpp. PyKeyHandler (renamed from PyScanCodeKeystroke).
# Also PyMouse module available.

from typing import List

class PyKeyHandler:
    def __init__(self) -> None: ...
    def PressKey(self, virtualKeyCode: int) -> None: ...
    def ReleaseKey(self, virtualKeyCode: int) -> None: ...
    def PushKey(self, virtualKeyCode: int) -> None: ...
    def PressKeyCombo(self, keys: List[int]) -> None: ...
    def ReleaseKeyCombo(self, keys: List[int]) -> None: ...
    def PushKeyCombo(self, keys: List[int]) -> None: ...
