# PyOverlay stub - Reforged Native surface.
# Matches overlay_bindings.cpp. Vec2f/Vec3f replace legacy Point2D/Point3D.

from typing import List, Tuple, overload

class Vec2f:
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

class Vec3f:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...

class Overlay:
    def __init__(self) -> None: ...
    def RefreshDrawList(self) -> None: ...
    def GetMouseCoords(self) -> Vec2f: ...

    # --- ground height / z-planes -------------------------------------------
    # multi_plane=True (default): topmost surface across ALL planes (bridges/slopes
    # are planes > 0), stable regardless of the player's plane.
    # multi_plane=False: legacy altitude at the player's plane.
    def FindZ(self, x: float, y: float, pz: int = 0, multi_plane: bool = True) -> float: ...
    # Batched FindZ (path display, dozens/frame): plane list fetched once, single-plane fast path.
    def FindZBatch(self, points: List[Tuple[float, float]], multi_plane: bool = True) -> List[float]: ...
    def FindZPlane(self, x: float, y: float, z: int = 0) -> int: ...
    # Number of z-planes (pmaps); 0 if not ready. <= 1 => single-plane (cheap gate).
    def GetZPlaneCount(self) -> int: ...
    # Altitude at a SPECIFIC plane -> (covered, z). covered=False if no surface there.
    def QueryAltitudeAt(self, x: float, y: float, plane: int) -> Tuple[bool, float]: ...
    # Specialist: covered surface nearest ref_z (bridge-over vs under-bridge).
    def GroundZNearest(self, x: float, y: float, ref_z: float) -> float: ...
    def GroundZNearestBatch(self, points: List[Tuple[float, float]], ref_zs: List[float]) -> List[float]: ...
    # Option B: plane-less navmesh/terrain height (does NOT add bridge/slope props).
    def GroundZWalkable(self, x: float, y: float) -> float: ...
    def GroundZWalkableBatch(self, points: List[Tuple[float, float]]) -> List[float]: ...

    # --- coordinate conversions ---------------------------------------------
    def WorldToScreen(self, x: float, y: float, z: float) -> Vec2f: ...
    def GetMouseWorldPos(self) -> Vec3f: ...
    def GamePosToWorldMap(self, x: float, y: float) -> Vec2f: ...
    def WorldMapToGamePos(self, x: float, y: float) -> Vec2f: ...
    def WorldMapToScreen(self, x: float, y: float) -> Vec2f: ...
    def ScreenToWorldMap(self, x: float, y: float) -> Vec2f: ...
    def GameMapToScreen(self, x: float, y: float) -> Vec2f: ...
    def ScreenToGameMapPos(self, x: float, y: float) -> Vec2f: ...
    def NormalizedScreenToScreen(self, norm_x: float, norm_y: float) -> Vec2f: ...
    def ScreenToNormalizedScreen(self, screen_x: float, screen_y: float) -> Vec2f: ...
    def NormalizedScreenToWorldMap(self, norm_x: float, norm_y: float) -> Vec2f: ...
    def NormalizedScreenToGameMap(self, norm_x: float, norm_y: float) -> Vec2f: ...
    def GamePosToNormalizedScreen(self, x: float, y: float) -> Vec2f: ...

    # --- immediate-mode drawing ---------------------------------------------
    def BeginDraw(self, name: str = "", x: float = 0.0, y: float = 0.0,
                  width: float = 0.0, height: float = 0.0) -> None: ...
    def EndDraw(self) -> None: ...
    def DrawLine(self, from_: Vec2f, to: Vec2f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawLine3D(self, from_: Vec3f, to: Vec3f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawTriangle(self, p1: Vec2f, p2: Vec2f, p3: Vec2f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawTriangle3D(self, p1: Vec3f, p2: Vec3f, p3: Vec3f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawTriangleFilled(self, p1: Vec2f, p2: Vec2f, p3: Vec2f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawTriangleFilled3D(self, p1: Vec3f, p2: Vec3f, p3: Vec3f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawQuad(self, p1: Vec2f, p2: Vec2f, p3: Vec2f, p4: Vec2f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawQuad3D(self, p1: Vec3f, p2: Vec3f, p3: Vec3f, p4: Vec3f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawQuadFilled(self, p1: Vec2f, p2: Vec2f, p3: Vec2f, p4: Vec2f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawQuadFilled3D(self, p1: Vec3f, p2: Vec3f, p3: Vec3f, p4: Vec3f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawPoly(self, center: Vec2f, radius: float, color: int = 0xFFFFFFFF, numSegments: int = 12, thickness: float = 1.0) -> None: ...
    def DrawPoly3D(self, center: Vec3f, radius: float, color: int = 0xFFFFFFFF, numSegments: int = 12, thickness: float = 1.0, autoZ: bool = True) -> None: ...
    def DrawPolyFilled(self, center: Vec2f, radius: float, color: int = 0xFFFFFFFF, numSegments: int = 12) -> None: ...
    def DrawPolyFilled3D(self, center: Vec3f, radius: float, color: int = 0xFFFFFFFF, numSegments: int = 12, autoZ: bool = True) -> None: ...
    def DrawCubeOutline(self, center: Vec3f, size: float, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawCubeFilled(self, center: Vec3f, size: float, color: int = 0xFFFFFFFF) -> None: ...
    def DrawText(self, position: Vec2f, text: str, color: int = 0xFFFFFFFF, centered: bool = True, scale: float = 1.0) -> None: ...
    def DrawText3D(self, position3D: Vec3f, text: str, color: int = 0xFFFFFFFF, autoZ: bool = True, centered: bool = True, scale: float = 1.0) -> None: ...
    def GetDisplaySize(self) -> Vec2f: ...
    def IsMouseClicked(self, button: int = 0) -> bool: ...
    def PushClipRect(self, x: float, y: float, x2: float, y2: float) -> None: ...
    def PopClipRect(self) -> None: ...

    # --- textures ------------------------------------------------------------
    @overload
    def DrawTexture(self, path: str, width: float = 32.0, height: float = 32.0) -> None: ...
    @overload
    def DrawTexture(self, path: str,
                    size: Tuple[float, float] = (32.0, 32.0),
                    uv0: Tuple[float, float] = (0.0, 0.0),
                    uv1: Tuple[float, float] = (1.0, 1.0),
                    tint: Tuple[int, int, int, int] = (255, 255, 255, 255),
                    border_col: Tuple[int, int, int, int] = (0, 0, 0, 0)) -> None: ...
    @overload
    def DrawTexturedRect(self, x: float, y: float, width: float, height: float, texture_path: str) -> None: ...
    @overload
    def DrawTexturedRect(self, pos: Tuple[float, float], size: Tuple[float, float], texture_path: str,
                         uv0: Tuple[float, float] = (0.0, 0.0),
                         uv1: Tuple[float, float] = (1.0, 1.0),
                         tint: Tuple[int, int, int, int] = (255, 255, 255, 255)) -> None: ...
    def UpkeepTextures(self, timeout: int = 30) -> None: ...
    @overload
    def ImageButton(self, caption: str, file_path: str, width: float = 32.0, height: float = 32.0, frame_padding: int = 0) -> bool: ...
    @overload
    def ImageButton(self, caption: str, file_path: str,
                    size: Tuple[float, float] = (32.0, 32.0),
                    uv0: Tuple[float, float] = (0.0, 0.0),
                    uv1: Tuple[float, float] = (1.0, 1.0),
                    bg_color: Tuple[int, int, int, int] = (0, 0, 0, 0),
                    tint_color: Tuple[int, int, int, int] = (255, 255, 255, 255),
                    frame_padding: int = 0) -> bool: ...
    def DrawTextureInForegound(self, pos: Tuple[float, float] = (0.0, 0.0),
                               size: Tuple[float, float] = (100.0, 100.0),
                               texture_path: str = "",
                               uv0: Tuple[float, float] = (0.0, 0.0),
                               uv1: Tuple[float, float] = (1.0, 1.0),
                               tint: Tuple[int, int, int, int] = (255, 255, 255, 255)) -> None: ...
    def DrawTextureInDrawlist(self, pos: Tuple[float, float] = (0.0, 0.0),
                              size: Tuple[float, float] = (100.0, 100.0),
                              texture_path: str = "",
                              uv0: Tuple[float, float] = (0.0, 0.0),
                              uv1: Tuple[float, float] = (1.0, 1.0),
                              tint: Tuple[int, int, int, int] = (255, 255, 255, 255)) -> None: ...

class ScreenOverlay:
    def __init__(self) -> None: ...
    def create_overlay(self, ms: int = 0, destroy: bool = False) -> None: ...
    def destroy(self) -> None: ...
    def show(self, show: bool) -> None: ...
    def begin(self) -> None: ...
    def draw_rect(self, x: float, y: float, w: float, h: float, argb: int, thickness: float = 1.0) -> None: ...
    def draw_rect_filled(self, x: float, y: float, w: float, h: float, argb: int) -> None: ...
