# PyOverlay stub — Reforged Native surface (2026-07-06)
# Matches overlay_bindings.cpp. Vec2f/Vec3f replace legacy Point2D/Point3D.

from typing import Tuple

class Vec2f:
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

class Vec3f:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...

class Overlay:
    def __init__(self) -> None: ...
    def Begin(self) -> None: ...
    def End(self) -> None: ...
    def DrawPoint(self, x: float, y: float, color: int = 0xFFFFFFFF, size: float = 1.0) -> None: ...
    def DrawLine(self, x1: float, y1: float, x2: float, y2: float, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawRect(self, x: float, y: float, w: float, h: float, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawRectFilled(self, x: float, y: float, w: float, h: float, color: int = 0xFFFFFFFF) -> None: ...

class ScreenOverlay:
    def __init__(self) -> None: ...
    def create_overlay(self, ms: int = 0, destroy: bool = False) -> None: ...
    def destroy(self) -> None: ...
    def show(self, show: bool) -> None: ...
    def begin(self) -> None: ...
    def draw_rect(self, x: float, y: float, w: float, h: float, argb: int, thickness: float = 1.0) -> None: ...
    def draw_rect_filled(self, x: float, y: float, w: float, h: float, argb: int) -> None: ...
