# PyParty stub — Reforged Native surface (2026-07-06)
# Matches party_bindings.cpp. All legacy classes preserved.
# NOTE: HeroPartyMember.hero_id is int (not Hero object) in Reforged.
#       HeroPartyMember.primary/secondary are int (not Profession).

from typing import List, Tuple
from enum import IntEnum

class HeroType(IntEnum):
    NoHero: int = 0
    Norgu: int
    Goren: int
    Tahlkora: int
    MasterOfWhispers: int
    AcolyteJin: int
    Koss: int
    Dunkoro: int
    AcolyteSousuke: int
    Melonni: int
    ZhedShadowhoof: int
    GeneralMorgahn: int
    MargridTheSly: int
    Zenmai: int
    Olias: int
    Razah: int
    MOX: int
    KeiranThackeray: int
    Jora: int
    PyreFierceshot: int
    Anton: int
    Livia: int
    Hayda: int
    Kahmu: int
    Gwen: int
    Xandra: int
    Vekk: int
    Ogden: int
    MercenaryHero1: int
    MercenaryHero2: int
    MercenaryHero3: int
    MercenaryHero4: int
    MercenaryHero5: int
    MercenaryHero6: int
    MercenaryHero7: int
    MercenaryHero8: int
    Miku: int
    ZeiRi: int

class Hero:
    def __init__(self, hero_id_or_name: int | str) -> None: ...
    def GetID(self) -> int: ...
    def GetName(self) -> str: ...
    def GetProfession(self) -> int: ...
    def FlagHero(self, idx: int) -> bool: ...

class PartyTick:
    def __init__(self, ticked: bool = False) -> None: ...
    def IsTicked(self) -> bool: ...
    def SetTicked(self, ticked: bool) -> None: ...
    def ToggleTicked(self) -> None: ...
    def SetTickToggle(self, enable: bool) -> None: ...

class PlayerPartyMember:
    login_number: int
    called_target_id: int
    is_connected: bool
    is_ticked: bool
    def __init__(self, login_number: int = 0, called_target_id: int = 0, is_connected: bool = False, is_ticked: bool = False) -> None: ...

class HeroPartyMember:
    agent_id: int
    owner_player_id: int
    hero_id: int       # NOTE: int in Reforged (was Hero object in legacy)
    level: int
    primary: int        # NOTE: int in Reforged (was Profession in legacy)
    secondary: int      # NOTE: int in Reforged (was Profession in legacy)
    def __init__(self, agent_id: int = 0, owner_player_id: int = 0, hero_id: int = 0, level: int = 0) -> None: ...

class HenchmanPartyMember:
    agent_id: int
    profession: int
    level: int
    def __init__(self, agent_id: int = 0, profession: int = 0, level: int = 0) -> None: ...

class PetInfo:
    agent_id: int
    owner_agent_id: int
    pet_name: str
    model_file_id1: int
    model_file_id2: int
    behavior: int
    locked_target_id: int
    def __init__(self, owner_agent_id: int) -> None: ...

class PyParty:
    party_id: int
    players: List[PlayerPartyMember]
    heroes: List[HeroPartyMember]
    henchmen: List[HenchmanPartyMember]
    others: List[int]
    is_in_hard_mode: bool
    is_hard_mode_unlocked: bool
    party_size: int
    party_player_count: int
    party_hero_count: int
    party_henchman_count: int
    is_party_defeated: bool
    is_party_loaded: bool
    is_party_leader: bool
    tick: PartyTick

    def __init__(self) -> None: ...
    def GetContext(self) -> None: ...
    def ReturnToOutpost(self) -> bool: ...
    def SetHardMode(self, flag: bool) -> bool: ...
    def RespondToPartyRequest(self, party_id: int, accept: bool) -> bool: ...
    def AddHero(self, hero_id: int) -> bool: ...
    def KickHero(self, hero_id: int) -> bool: ...
    def KickAllHeroes(self) -> bool: ...
    def AddHenchman(self, henchman_id: int) -> bool: ...
    def KickHenchman(self, henchman_id: int) -> bool: ...
    def KickPlayer(self, player_id: int) -> bool: ...
    def InvitePlayer(self, player_id: int) -> bool: ...
    def LeaveParty(self) -> bool: ...
    def UseHeroSkill(self, hero_agent_id: int, skill_slot: int, target_id: int) -> None: ...
    def SetHeroSkillAIEnabled(self, hero_agent_id: int, skill_slot: int, enabled: bool) -> bool: ...
    def FlagHero(self, agent_id: int, x: float, y: float) -> bool: ...
    def FlagAllHeroes(self, x: float, y: float) -> bool: ...
    def UnflagHero(self, agent_id: int) -> bool: ...
    def UnflagAllHeroes(self) -> bool: ...
    def IsHeroFlagged(self, hero: int) -> bool: ...
    def IsAllFlagged(self) -> bool: ...
    def GetAllFlagX(self) -> float: ...
    def GetAllFlagY(self) -> float: ...
    def GetHeroAgentID(self, hero_index: int) -> int: ...
    def GetAgentHeroID(self, agent_id: int) -> int: ...
    def GetAgentIDByLoginNumber(self, login_number: int) -> int: ...
    def GetPlayerNameByLoginNumber(self, login_number: int) -> str: ...
    def SearchParty(self, search_type: int, advertisement: str) -> bool: ...
    def SearchPartyCancel(self) -> bool: ...
    def SearchPartyReply(self, accept: bool) -> bool: ...
    def SetHeroBehavior(self, agent_id: int, behavior: int) -> None: ...
    def SetPetBehavior(self, behavior: int, lock_target_id: int) -> None: ...
    def GetPetInfo(self, owner_agent_id: int) -> PetInfo: ...
    def GetIsPlayerTicked(self, player_id: int) -> bool: ...
    def GetPartyContextPtr(self) -> int: ...

# ── Module-level free functions ──
def set_tick_toggle(enable: bool) -> None: ...
def tick(flag: bool = True) -> bool: ...
def get_party_size() -> int: ...
def get_party_player_count() -> int: ...
def get_party_hero_count() -> int: ...
def get_party_henchman_count() -> int: ...
def get_is_party_defeated() -> bool: ...
def get_is_party_in_hard_mode() -> bool: ...
def get_is_hard_mode_unlocked() -> bool: ...
def get_is_party_ticked() -> bool: ...
def get_is_player_ticked(player_index: int = 0xFFFFFFFF) -> bool: ...
def get_is_player_loaded(player_index: int = 0xFFFFFFFF) -> bool: ...
def get_is_party_loaded() -> bool: ...
def get_is_leader() -> bool: ...
def set_hard_mode(flag: bool) -> bool: ...
def return_to_outpost() -> bool: ...
def respond_to_party_request(party_id: int, accept: bool) -> bool: ...
def leave_party() -> bool: ...
def add_hero(hero_id: int) -> bool: ...
def kick_hero(hero_id: int) -> bool: ...
def kick_all_heroes() -> bool: ...
def add_henchman(agent_id: int) -> bool: ...
def kick_henchman(agent_id: int) -> bool: ...
def invite_player_by_id(player_id: int) -> bool: ...
def invite_player_by_name(player_name: str) -> bool: ...
def kick_player(player_id: int) -> bool: ...
def flag_hero(hero_index: int, x: float, y: float) -> bool: ...
def flag_hero_agent(agent_id: int, x: float, y: float) -> bool: ...
def unflag_hero(hero_index: int) -> bool: ...
def flag_all(x: float, y: float) -> bool: ...
def unflag_all() -> bool: ...
def set_hero_behavior(agent_id: int, behavior: int) -> bool: ...
def set_hero_skill_ai_enabled(hero_agent_id: int, skill_slot: int, enabled: bool) -> bool: ...
def set_pet_behavior(behavior: int, lock_target_id: int = 0) -> bool: ...
def get_hero_agent_id(hero_index: int) -> int: ...
def get_agent_hero_id(agent_id: int) -> int: ...
def search_party(search_type: int, advertisement: str = "") -> bool: ...
def search_party_cancel() -> bool: ...
def search_party_reply(accept: bool) -> bool: ...
