# PyPlayer stub — Reforged Native surface (2026-07-06)
# Matches player_bindings.cpp. PyPlayer class preserved + module-level free functions.

from typing import List, Tuple
from enum import IntEnum

class PlayerStatus(IntEnum):
    Offline: int = 0
    Online: int = 1
    DND: int = 2
    Away: int = 3

class PyPlayer:
    id: int
    agent: int
    target_id: int
    mouse_over_id: int
    observing_id: int
    account_name: str
    account_email: str
    player_uuid: Tuple[int, int, int, int]
    wins: int
    losses: int
    rating: int
    qualifier_points: int
    rank: int
    tournament_reward_points: int
    morale: int
    party_morale: List[Tuple[int, int]]
    experience: int
    level: int
    current_kurzick: int
    total_earned_kurzick: int
    max_kurzick: int
    current_luxon: int
    total_earned_luxon: int
    max_luxon: int
    current_imperial: int
    total_earned_imperial: int
    max_imperial: int
    current_balth: int
    total_earned_balth: int
    max_balth: int
    current_skill_points: int
    total_earned_skill_points: int
    missions_completed: List[int]
    missions_bonus: List[int]
    missions_completed_hm: List[int]
    missions_bonus_hm: List[int]
    controlled_minions: List[Tuple[int, int]]
    unlocked_maps: List[int]
    learnable_character_skills: List[int]
    unlocked_character_skills: List[int]

    def __init__(self) -> None: ...
    def GetContext(self) -> None: ...
    def SendDialog(self, dialog_id: int) -> None: ...
    def ChangeTarget(self, target_id: int) -> bool: ...
    def InteractAgent(self, agent_id: int, call_target: bool) -> bool: ...
    def CallTarget(self, agent_id: int) -> bool: ...
    def IsAgentIDValid(self, agent_id: int) -> bool: ...
    def GetChatHistory(self) -> List[str]: ...
    def RequestChatHistory(self) -> None: ...
    def IsChatHistoryReady(self) -> bool: ...
    def Istyping(self) -> bool: ...
    def SendChatCommand(self, msg: str) -> None: ...
    def SendChat(self, channel: str, msg: str) -> None: ...
    def SendWhisper(self, name: str, msg: str) -> None: ...
    def SendFakeChat(self, channel: int, message: str) -> None: ...
    def SendFakeChatColored(self, channel: int, message: str, r: int, g: int, b: int) -> None: ...
    def GetPlayerStatus(self) -> int: ...
    def SetPlayerStatus(self, status: int) -> bool: ...

# ── Module-level free functions ──
def set_active_title(title_id: int) -> bool: ...
def remove_active_title() -> bool: ...
def get_active_title_id() -> int: ...
def deposit_faction(allegiance: int) -> bool: ...
def get_player_agent_id(player_id: int) -> int: ...
def get_amount_of_players_in_instance() -> int: ...
def get_player_number() -> int: ...
def get_player_name(player_id: int = 0) -> str: ...
def change_second_profession(profession: int, hero_index: int = 0) -> bool: ...
def get_title_ids() -> list: ...
