# PySystem stub — Reforged Native surface (2026-07-06)
# Authoritative module for console logging, shared memory name, tick count,
# script lifecycle, widget manager, window control, and environment queries.

from typing import Any
from enum import IntEnum

class MessageType(IntEnum):
    Info: int
    Warning: int
    Error: int
    Debug: int
    Success: int
    Performance: int
    Notice: int
    Hook: int

class ConsoleMessage:
    timestamp: int
    display_timestamp: str
    module_name: str
    level: str
    message_type: MessageType
    message: str

def get_tick_count64() -> int: ...
def get_shared_memory_name() -> str: ...
def get_credits() -> str: ...
def get_license() -> str: ...
def change_working_directory(path: str) -> None: ...
def request_shutdown_prompt() -> None: ...
def cancel_shutdown_prompt() -> None: ...
def is_shutdown_prompt_pending() -> bool: ...
def in_character_select_screen() -> bool: ...
def has_account_email() -> bool: ...
def get_account_email() -> str: ...
def get_settings_directory() -> str: ...

class Console:
    MessageType = MessageType

    @staticmethod
    def Log(sender: str, message: str, message_type: MessageType = MessageType.Info) -> None: ...

    @staticmethod
    def get_projects_path() -> str: ...

    @staticmethod
    def get_gw_window_handle() -> int: ...

    @staticmethod
    def write(module_name: str, message: str, level: str = "INFO") -> None: ...

    @staticmethod
    def get_messages(message_type: MessageType | None = None) -> list[ConsoleMessage]: ...

    @staticmethod
    def filter_messages(module_name: str = "", level: str = "", contains: str = "") -> list[ConsoleMessage]: ...

    @staticmethod
    def clear_messages() -> None: ...

    @staticmethod
    def set_output_to_file(enabled: bool) -> None: ...

    @staticmethod
    def get_output_to_file() -> bool: ...

    @staticmethod
    def set_draw_console(enabled: bool) -> None: ...

    @staticmethod
    def get_draw_console() -> bool: ...

    @staticmethod
    def set_draw_compact_console(enabled: bool) -> None: ...

    @staticmethod
    def get_draw_compact_console() -> bool: ...

    @staticmethod
    def toggle_console() -> None: ...

    @staticmethod
    def toggle_compact_console() -> None: ...

class environment:
    @staticmethod
    def get_gw_window_handle() -> int: ...
    @staticmethod
    def get_projects_path() -> str: ...

class window:
    @staticmethod
    def resize_window(width: int, height: int) -> None: ...
    @staticmethod
    def move_window_to(x: int, y: int) -> None: ...
    @staticmethod
    def set_window_geometry(x: int, y: int, width: int, height: int) -> None: ...
    @staticmethod
    def get_window_rect() -> tuple[int, int, int, int]: ...
    @staticmethod
    def get_client_rect() -> tuple[int, int, int, int]: ...
    @staticmethod
    def set_window_active() -> None: ...
    @staticmethod
    def set_window_title(title: str) -> None: ...
    @staticmethod
    def is_window_active() -> bool: ...
    @staticmethod
    def is_window_minimized() -> bool: ...
    @staticmethod
    def is_window_in_background() -> bool: ...
    @staticmethod
    def set_borderless(enable: bool) -> None: ...
    @staticmethod
    def set_always_on_top(enable: bool) -> None: ...
    @staticmethod
    def flash_window(repeat_count: int = 1) -> None: ...
    @staticmethod
    def request_attention() -> None: ...
    @staticmethod
    def get_z_order() -> int: ...
    @staticmethod
    def set_z_order(insert_after: int = 0) -> None: ...
    @staticmethod
    def send_window_to_back() -> None: ...
    @staticmethod
    def bring_window_to_front() -> None: ...
    @staticmethod
    def transparent_click_through(enable: bool) -> None: ...
    @staticmethod
    def adjust_window_opacity(alpha: int) -> None: ...
    @staticmethod
    def hide_window() -> None: ...
    @staticmethod
    def show_window() -> None: ...

class script_control:
    @staticmethod
    def load(path: str) -> bool: ...
    @staticmethod
    def run() -> None: ...
    @staticmethod
    def stop() -> None: ...
    @staticmethod
    def pause() -> None: ...
    @staticmethod
    def resume() -> None: ...
    @staticmethod
    def status() -> str: ...
    @staticmethod
    def defer_load_and_run(path: str, delay_ms: int = 1000) -> None: ...
    @staticmethod
    def defer_stop_load_and_run(path: str, delay_ms: int = 1000) -> None: ...
    @staticmethod
    def defer_stop_and_run(delay_ms: int = 1000) -> None: ...

class widget_manager:
    @staticmethod
    def start() -> None: ...
    @staticmethod
    def stop() -> None: ...
    @staticmethod
    def status() -> str: ...
